const config = require('../config');
const menuData = [
    {
      "title": "用户管理",
      "name": "UserManager",
      "permCode": null,
      "effect": false,
      "icon": "ant-design:user",
      "hidden": false,
      "hideChildrenInMenu": false,
      "component": "Layout",
      "path": "/account/manager",
      "redirect": "",
      "menuType": 0,
      "keepAlive": true,
      "targetOutside": false,
      "hiddenHeaderContent": false,
      "remark": null,
      "internal": false,
      "children": [
        {
          "title": "注册用户",
          "name": "RegUserList",
          "permCode": null,
          "effect": false,
          "icon": "",
          "hidden": false,
          "hideChildrenInMenu": false,
          "component": "account/manager/RegUserList",
          "path": "/account/manager/list",
          "redirect": "",
          "menuType": 1,
          "keepAlive": true,
          "targetOutside": false,
          "hiddenHeaderContent": false,
          "remark": null,
          "internal": false,
          "children": null
        },
        {
          "title": "创作用户",
          "name": "CreationUserList",
          "permCode": null,
          "effect": false,
          "icon": "",
          "hidden": false,
          "hideChildrenInMenu": false,
          "component": "account/creative/CreaTive",
          "path": "/account/creative/list",
          "redirect": "",
          "menuType": 1,
          "keepAlive": true,
          "targetOutside": false,
          "hiddenHeaderContent": false,
          "remark": null,
          "internal": false,
          "children": null
        },
        {
          "title": "共创用户",
          "name": "collManager",
          "permCode": null,
          "effect": false,
          "icon": "",
          "hidden": !config.IS_PARENT,
          "hideChildrenInMenu": false,
          "component": "account/collab/CollabList",
          "path": "/account/collab/list",
          "redirect": "",
          "menuType": 1,
          "keepAlive": true,
          "targetOutside": false,
          "hiddenHeaderContent": false,
          "remark": null,
          "internal": false,
          "children": null
        },
      ]
    },
    {
      "title": "企业管理",
      "name": "EnterpriseManager",
      "permCode": null,
      "effect": false,
      "icon": "ant-design:bank",
      "hidden": false,
      "hideChildrenInMenu": false,
      "component": "Layout",
      "path": "/enterprise/manager",
      "redirect": "",
      "menuType": 0,
      "keepAlive": true,
      "targetOutside": false,
      "hiddenHeaderContent": false,
      "remark": null,
      "internal": false,
      "children": [
        {
          "title": "企业列表",
          "name": "RegEnterpriseList",
          "permCode": null,
          "effect": false,
          "icon": "",
          "hidden": false,
          "hideChildrenInMenu": false,
          "component": "enterprise/manager/RegEnterpriseList",
          "path": "/enterprise/manager/list",
          "redirect": "",
          "menuType": 1,
          "keepAlive": true,
          "targetOutside": false,
          "hiddenHeaderContent": false,
          "remark": null,
          "internal": false,
          "children": null
        },
        {
          "title": "企业人员",
          "name": "EnterpriseMembers",
          "permCode": null,
          "effect": false,
          "icon": "",
          "hidden": false,
          "hideChildrenInMenu": false,
          "component": "enterprise/members/EnterpriseMembersList",
          "path": "/enterprise/manager/members",
          "redirect": "",
          "menuType": 1,
          "keepAlive": true,
          "targetOutside": false,
          "hiddenHeaderContent": false,
          "remark": null,
          "internal": false,
          "children": null
        }
      ]
    },
    {
      "title": "市场管理",
      "name": "ShopManager",
      "permCode": null,
      "effect": false,
      "icon": "ant-design:shop",
      "hidden": false,
      "hideChildrenInMenu": false,
      "component": "Layout",
      "path": "/shop/project",
      "redirect": "",
      "menuType": 0,
      "keepAlive": true,
      "targetOutside": false,
      "hiddenHeaderContent": false,
      "remark": null,
      "internal": false,
      "children": [
        {
          "title": "AI项目",
          "name": "AIProject",
          "permCode": null,
          "effect": false,
          "icon": "",
          "hidden": false,
          "hideChildrenInMenu": true,
          "component": "shop/project/AIProjectList",
          "path": "/shop/project/list",
          "redirect": "",
          "menuType": 1,
          "keepAlive": true,
          "targetOutside": false,
          "hiddenHeaderContent": false,
          "remark": null,
          "internal": false,
          "children": null
        },
        {
          "title": "待审核项目",
          "name": "MultipleRevisions",
          "permCode": null,
          "effect": false,
          "icon": "",
          "hidden": false,
          "hideChildrenInMenu": true,
          "component": "shop/multiplerevisions/MultipleRevisionsList",
          "path": "/shop/multiplerevisions/multiplelist",
          "redirect": "",
          "menuType": 1,
          "keepAlive": true,
          "targetOutside": false,
          "hiddenHeaderContent": false,
          "remark": null,
          "internal": false,
          "children": null
        },
        {
          "title": "市场资源",
          "name": "ModelPluginWorkFlow",
          "permCode": null,
          "effect": false,
          "icon": "",
          "hidden": false,
          "hideChildrenInMenu": true,
          "component": "shop/modplnwork/ResourcesList",
          "path": "/shop/modplnwork/modplnworklist",
          "redirect": "",
          "menuType": 1,
          "keepAlive": true,
          "targetOutside": false,
          "hiddenHeaderContent": false,
          "remark": null,
          "internal": false,
          "children": null
        },
        {
          "title": "待审核资源",
          "name": "ReviewModelPluginWorkFlow",
          "permCode": null,
          "effect": false,
          "icon": "",
          "hidden": false,
          "hideChildrenInMenu": true,
          "component": "shop/reviewmodplnwork/ResourcesList",
          "path": "/shop/reviewmodplnwork/reviewmodplnworklist",
          "redirect": "",
          "menuType": 1,
          "keepAlive": true,
          "targetOutside": false,
          "hiddenHeaderContent": false,
          "remark": null,
          "internal": false,
          "children": null
        }
      ]
    },
    {
      "title": "消息管理",
      "name": "Message",
      "permCode": null,
      "effect": false,
      "icon": "ant-design:message-outlined",
      "hidden": false,
      "hideChildrenInMenu": false,
      "component": "Layout",
      "path": "/shop/chat",
      "redirect": "",
      "menuType": 0,
      "keepAlive": true,
      "targetOutside": false,
      "hiddenHeaderContent": false,
      "remark": null,
      "internal": false,
      "children": [
        {
          "title": "评论管理",
          "name": "CommentManager",
          "permCode": null,
          "effect": false,
          "icon": "",
          "hidden": false,
          "hideChildrenInMenu": true,
          "component": "shop/comment/list/CommentList",
          "path": "/shop/comment/list",
          "redirect": "",
          "menuType": 1,
          "keepAlive": true,
          "targetOutside": false,
          "hiddenHeaderContent": false,
          "remark": null,
          "internal": false,
          "children": null
        },
        {
          "title": "评论举报管理",
          "name": "CommentReportManager",
          "permCode": null,
          "effect": false,
          "icon": "",
          "hidden": false,
          "hideChildrenInMenu": true,
          "component": "shop/comment/report/CommentReportList",
          "path": "/shop/comment/report",
          "redirect": "",
          "menuType": 1,
          "keepAlive": true,
          "targetOutside": false,
          "hiddenHeaderContent": false,
          "remark": null,
          "internal": false,
          "children": null
        },
        {
          "title": "消息管理",
          "name": "ChatManager",
          "permCode": null,
          "effect": false,
          "icon": "",
          "hidden": false,
          "hideChildrenInMenu": true,
          "component": "shop/chat/list/ChatList",
          "path": "/shop/chat/list",
          "redirect": "",
          "menuType": 1,
          "keepAlive": true,
          "targetOutside": false,
          "hiddenHeaderContent": false,
          "remark": null,
          "internal": false,
          "children": null
        }
      ]
    },
    {
      "title": "支付配置",
      "name": "PayConfig",
      "permCode": null,
      "effect": false,
      "icon": "ant-design:setting-filled",
      "hidden": false,
      "hideChildrenInMenu": false,
      "component": "Layout",
      "path": "/pay/config",
      "redirect": "",
      "menuType": 0,
      "keepAlive": true,
      "targetOutside": false,
      "hiddenHeaderContent": false,
      "remark": null,
      "internal": false,
      "children": [
        // {
        //   "title": "平台配置",
        //   "name": "PayPlatformConfig",
        //   "permCode": null,
        //   "effect": false,
        //   "icon": "",
        //   "hidden": false,
        //   "hideChildrenInMenu": false,
        //   "component": "payment/system/platform/PayPlatformConfig",
        //   "path": "/pay/config/platform",
        //   "redirect": "",
        //   "menuType": 1,
        //   "keepAlive": true,
        //   "targetOutside": false,
        //   "hiddenHeaderContent": false,
        //   "remark": null,
        //   "internal": false,
        //   "children": null
        // },
        {
          "title": "平台配置",
          "name": "PayPlatformConfigV2",
          "permCode": null,
          "effect": false,
          "icon": "",
          "hidden": false,
          "hideChildrenInMenu": false,
          "component": "payment/system/platformv2/PayPlatformConfigV2",
          "path": "/pay/config/platformv2",
          "redirect": "",
          "menuType": 1,
          "keepAlive": true,
          "targetOutside": false,
          "hiddenHeaderContent": false,
          "remark": null,
          "internal": false,
          "children": null
        },
        {
          "title": "税收配置",
          "name": "TaxConfig",
          "permCode": null,
          "effect": false,
          "icon": "",
          "hidden": false,
          "hideChildrenInMenu": false,
          "component": "payment/system/tax/TaxConfig",
          "path": "/pay/config/tax",
          "redirect": "",
          "menuType": 1,
          "keepAlive": true,
          "targetOutside": false,
          "hiddenHeaderContent": false,
          "remark": null,
          "internal": false,
          "children": null
        },
        {
          "title": "共创者配置",
          "name": "PayCollabConfig",
          "permCode": null,
          "effect": false,
          "icon": "",
          "hidden": !config.IS_PARENT,
          "hideChildrenInMenu": false,
          "component": "payment/system/collab/PayCollabConfig",
          "path": "/pay/config/collab",
          "redirect": "",
          "menuType": 1,
          "keepAlive": true,
          "targetOutside": false,
          "hiddenHeaderContent": false,
          "remark": null,
          "internal": false,
          "children": null
        },
        {
          "title": "通道配置",
          "name": "ChannelPayConfigList",
          "permCode": null,
          "effect": false,
          "icon": "",
          "hidden": false,
          "hideChildrenInMenu": false,
          "component": "payment/channel/config/ChannelPayConfigList",
          "path": "/pay/config/channelpay",
          "redirect": "",
          "menuType": 1,
          "keepAlive": true,
          "targetOutside": false,
          "hiddenHeaderContent": false,
          "remark": null,
          "internal": false,
          "children": null
        },
      ]
    },

    {
      "title": "对象存储",
      "name": "OssConfig",
      "permCode": null,
      "effect": false,
      "icon": "ant-design:cloud-download-outlined",
      "hidden": false,
      "hideChildrenInMenu": false,
      "component": "Layout",
      "path": "/oss/config",
      "redirect": "",
      "menuType": 0,
      "keepAlive": true,
      "targetOutside": false,
      "hiddenHeaderContent": false,
      "remark": null,
      "internal": false,
      "children": [
        {
          "title": "阿里OSS配置",
          "name": "OssPlatformConfig",
          "permCode": null,
          "effect": false,
          "icon": "",
          "hidden": false,
          "hideChildrenInMenu": false,
          "component": "oss/config/alipay/OssPlatformConfig",
          "path": "/oss/config/alipay/platform",
          "redirect": "",
          "menuType": 1,
          "keepAlive": true,
          "targetOutside": false,
          "hiddenHeaderContent": false,
          "remark": null,
          "internal": false,
          "children": null
        },
        {
          "title": "123网盘配置",
          "name": "123OssPlatformConfig",
          "permCode": null,
          "effect": false,
          "icon": "",
          "hidden": false,
          "hideChildrenInMenu": false,
          "component": "oss/config/123/OssPlatformConfig",
          "path": "/oss/config/123/platform",
          "redirect": "",
          "menuType": 1,
          "keepAlive": true,
          "targetOutside": false,
          "hiddenHeaderContent": false,
          "remark": null,
          "internal": false,
          "children": null
        }
      ]
    },
    {
      "title": "优惠管理",
      "name": "DiscountManager",
      "permCode": null,
      "effect": false,
      "icon": "ant-design:gift-outlined",
      "hidden": false,
      "hideChildrenInMenu": false,
      "component": "Layout",
      "path": "/discount/manager",
      "redirect": "",
      "menuType": 0,
      "keepAlive": true,
      "targetOutside": false,
      "hiddenHeaderContent": false,
      "remark": null,
      "internal": false,
      "children": [
        {
          "title": "优惠审核",
          "name": "DiscountReview",
          "permCode": null,
          "effect": false,
          "icon": "",
          "hidden": false,
          "hideChildrenInMenu": false,
          "component": "payment/discount/review/DiscountApply",
          "path": "/discount/manager/review",
          "redirect": "",
          "menuType": 1,
          "keepAlive": true,
          "targetOutside": false,
          "hiddenHeaderContent": false,
          "remark": null,
          "internal": false,
          "children": null
        },
        {
          "title": "优惠记录",
          "name": "DiscountRecord",
          "permCode": null,
          "effect": false,
          "icon": "",
          "hidden": false,
          "hideChildrenInMenu": false,
          "component": "payment/discount/list/Discount",
          "path": "/discount/manager/list",
          "redirect": "",
          "menuType": 1,
          "keepAlive": true,
          "targetOutside": false,
          "hiddenHeaderContent": false,
          "remark": null,
          "internal": false,
          "children": null
        }
      ]
    },
    {
      "title": "订单管理",
      "name": "PayOrder",
      "permCode": null,
      "effect": false,
      "icon": "ant-design:wallet-outlined",
      "hidden": false,
      "hideChildrenInMenu": false,
      "component": "Layout",
      "path": "/pay/order",
      "redirect": "",
      "menuType": 0,
      "keepAlive": true,
      "targetOutside": false,
      "hiddenHeaderContent": false,
      "remark": null,
      "internal": false,
      "children": [
        {
          "title": "支付订单",
          "name": "PayOrderList",
          "permCode": null,
          "effect": false,
          "icon": "",
          "hidden": false,
          "hideChildrenInMenu": false,
          "component": "payment/order/pay/PayOrderList",
          "path": "/pay/order/pay",
          "redirect": "",
          "menuType": 1,
          "keepAlive": true,
          "targetOutside": false,
          "hiddenHeaderContent": false,
          "remark": null,
          "internal": false,
          "children": null
        },
        {
          "title": "收益核验",
          "name": "UserOrderList",
          "permCode": null,
          "effect": false,
          "icon": "",
          "hidden": false,
          "hideChildrenInMenu": false,
          "component": "payment/order/userorderreview/PayOrderList",
          "path": "/pay/order/userorderpay",
          "redirect": "",
          "menuType": 1,
          "keepAlive": true,
          "targetOutside": false,
          "hiddenHeaderContent": false,
          "remark": null,
          "internal": false,
          "children": null
        },
        {
          "title": "提现申请",
          "name": "WithdrawOrderList",
          "permCode": null,
          "effect": false,
          "icon": "",
          "hidden": false,
          "hideChildrenInMenu": false,
          "component": "payment/order/withdraw/PayOrderList",
          "path": "/pay/order/withdraw",
          "redirect": "",
          "menuType": 1,
          "keepAlive": true,
          "targetOutside": false,
          "hiddenHeaderContent": false,
          "remark": null,
          "internal": false,
          "children": null
        }
      ]
    },
    {
      "title": "基础管理",
      "name": "EventUpdate",
      "permCode": null,
      "effect": false,
      "icon": "ant-design:setting-filled",
      "hidden": false,
      "hideChildrenInMenu": false,
      "component": "Layout",
      "path": "/eventupdate/order",
      "redirect": "",
      "menuType": 0,
      "keepAlive": true,
      "targetOutside": false,
      "hiddenHeaderContent": false,
      "remark": null,
      "internal": false,
      "children": [
        {
          "title": "信息屏蔽",
          "name": "messageBlock",
          "permCode": null,
          "effect": false,
          "icon": "",
          "hidden": false,
          "hideChildrenInMenu": false,
          "component": "eventupdate/order/messageblock/MessageBlockList",
          "path": "/eventupdate/order/messageblock",
          "redirect": "",
          "menuType": 1,
          "keepAlive": true,
          "targetOutside": false,
          "hiddenHeaderContent": false,
          "remark": null,
          "internal": false,
          "children": null
        },
        {
          "title": "更新管理",
          "name": "EventUpdateList",
          "permCode": null,
          "effect": false,
          "icon": "",
          "hidden": false,
          "hideChildrenInMenu": false,
          "component": "eventupdate/order/update/EventUpdateList",
          "path": "/eventupdate/order/update",
          "redirect": "",
          "menuType": 1,
          "keepAlive": true,
          "targetOutside": false,
          "hiddenHeaderContent": false,
          "remark": null,
          "internal": false,
          "children": null
        },
        {
          "title": "检测更新",
          "name": "EventUpdateListNonForce",
          "permCode": null,
          "effect": false,
          "icon": "",
          "hidden": false,
          "hideChildrenInMenu": false,
          "component": "eventupdate/order/updatenonforce/EventUpdateList",
          "path": "/eventupdate/order/updatenonforce",
          "redirect": "",
          "menuType": 1,
          "keepAlive": true,
          "targetOutside": false,
          "hiddenHeaderContent": false,
          "remark": null,
          "internal": false,
          "children": null
        },
        {
          "title": "幻灯片管理",
          "name": "EventBannerList",
          "permCode": null,
          "effect": false,
          "icon": "",
          "hidden": false,
          "hideChildrenInMenu": false,
          "component": "eventupdate/order/banner/EventBannerList",
          "path": "/eventupdate/order/banner",
          "redirect": "",
          "menuType": 1,
          "keepAlive": true,
          "targetOutside": false,
          "hiddenHeaderContent": false,
          "remark": null,
          "internal": false,
          "children": null
        },
        {
          "title": "分享链接管理",
          "name": "EventShareList",
          "permCode": null,
          "effect": false,
          "icon": "",
          "hidden": false,
          "hideChildrenInMenu": false,
          "component": "eventupdate/order/share/EventShareList",
          "path": "/eventupdate/order/share",
          "redirect": "",
          "menuType": 1,
          "keepAlive": true,
          "targetOutside": false,
          "hiddenHeaderContent": false,
          "remark": null,
          "internal": false,
          "children": null
        }
      ]
    },
    // {
    //   "title": "数据记录",
    //   "name": "PayRecord",
    //   "permCode": null,
    //   "effect": false,
    //   "icon": "ant-design:profile-outlined",
    //   "hidden": false,
    //   "hideChildrenInMenu": false,
    //   "component": "Layout",
    //   "path": "/pay/record",
    //   "redirect": "",
    //   "menuType": 0,
    //   "keepAlive": true,
    //   "targetOutside": false,
    //   "hiddenHeaderContent": false,
    //   "remark": null,
    //   "internal": false,
    //   "children": [
    //     {
    //       "title": "回调记录",
    //       "name": "PayCallbackRecordList",
    //       "permCode": null,
    //       "effect": false,
    //       "icon": "",
    //       "hidden": false,
    //       "hideChildrenInMenu": false,
    //       "component": "payment/record/callback/PayCallbackRecordList",
    //       "path": "/pay/record/callback",
    //       "redirect": "",
    //       "menuType": 1,
    //       "keepAlive": true,
    //       "targetOutside": false,
    //       "hiddenHeaderContent": false,
    //       "remark": null,
    //       "internal": false,
    //       "children": null
    //     },
    //     {
    //       "title": "关闭记录",
    //       "name": "PayCloseRecordList",
    //       "permCode": null,
    //       "effect": false,
    //       "icon": "",
    //       "hidden": false,
    //       "hideChildrenInMenu": false,
    //       "component": "payment/record/close/PayCloseRecordList",
    //       "path": "/pay/record/close",
    //       "redirect": "",
    //       "menuType": 1,
    //       "keepAlive": true,
    //       "targetOutside": false,
    //       "hiddenHeaderContent": false,
    //       "remark": null,
    //       "internal": false,
    //       "children": null
    //     },
    //     {
    //       "title": "修复记录",
    //       "name": "PayRepairRecordList",
    //       "permCode": null,
    //       "effect": false,
    //       "icon": "",
    //       "hidden": false,
    //       "hideChildrenInMenu": false,
    //       "component": "payment/record/repair/PayRepairRecordList",
    //       "path": "/pay/record/repair",
    //       "redirect": "",
    //       "menuType": 1,
    //       "keepAlive": true,
    //       "targetOutside": false,
    //       "hiddenHeaderContent": false,
    //       "remark": null,
    //       "internal": false,
    //       "children": null
    //     },
    //     {
    //       "title": "同步记录",
    //       "name": "PaySyncRecordList",
    //       "permCode": null,
    //       "effect": false,
    //       "icon": "",
    //       "hidden": false,
    //       "hideChildrenInMenu": false,
    //       "component": "payment/record/sync/PaySyncRecordList",
    //       "path": "/pay/record/sync",
    //       "redirect": "",
    //       "menuType": 1,
    //       "keepAlive": true,
    //       "targetOutside": false,
    //       "hiddenHeaderContent": false,
    //       "remark": null,
    //       "internal": false,
    //       "children": null
    //     },
    //     {
    //       "title": "交易流水",
    //       "name": "TradeFlowRecordList",
    //       "permCode": null,
    //       "effect": false,
    //       "icon": "",
    //       "hidden": false,
    //       "hideChildrenInMenu": false,
    //       "component": "payment/record/flow/TradeFlowRecordList",
    //       "path": "/pay/record/flow",
    //       "redirect": "",
    //       "menuType": 1,
    //       "keepAlive": true,
    //       "targetOutside": false,
    //       "hiddenHeaderContent": false,
    //       "remark": null,
    //       "internal": false,
    //       "children": null
    //     }
    //   ]
    // },
    // {
    //   "title": "支付通知",
    //   "name": "PayNotic",
    //   "permCode": null,
    //   "effect": false,
    //   "icon": "ant-design:clock-circle-outlined",
    //   "hidden": false,
    //   "hideChildrenInMenu": false,
    //   "component": "Layout",
    //   "path": "/pay/notice",
    //   "redirect": "",
    //   "menuType": 0,
    //   "keepAlive": true,
    //   "targetOutside": false,
    //   "hiddenHeaderContent": false,
    //   "remark": null,
    //   "internal": false,
    //   "children": [
    //     {
    //       "title": "通知记录",
    //       "name": "ClientNoticeTaskList",
    //       "permCode": null,
    //       "effect": false,
    //       "icon": "",
    //       "hidden": false,
    //       "hideChildrenInMenu": false,
    //       "component": "payment/task/notice/ClientNoticeTaskList",
    //       "path": "/pay/notice/record",
    //       "redirect": "",
    //       "menuType": 1,
    //       "keepAlive": true,
    //       "targetOutside": false,
    //       "hiddenHeaderContent": false,
    //       "remark": null,
    //       "internal": false,
    //       "children": null
    //     }
    //   ]
    // },
  ];

module.exports = menuData
