export default {
  app: {
    title: 'AI Starter',
    title_no_admin: 'Run without Administrator Privileges',
    title_admin: 'Run as Administrator',
    tis_place_admin: 'Please run as administrator',
    menu_home: 'Home',
    menu_file: 'File',
    menu_ai_navigation: 'AI Hub',
    menu_discus: 'Discus',
    menu_setting: 'Settings',
    menu_support: 'Support',
    customer_service: 'Support',
    menu_light: 'Lightbulb',
    menu_market: 'Market',
    menu_terminal: "Terminal",
    menu_review: 'Review',
    menu_my: 'My',
    setting_project_dir: 'Set Project Root Directory',
    setting_project_dir_tis: 'Please select a directory for project files that does not contain Chinese characters or special characters. Do not set the software installation directory and the project root directory in the same location to prevent installed projects from being deleted during upgrades or uninstallation. It is recommended to choose a disk with sufficient space.',
    setting_project_dir_select: 'Select Directory',
    setting_preferences_title: 'Preferences',
    setting_lang: 'Language Settings',
    setting_dir: 'Project Root Directory',
    setting_dev: 'Developer Options',
    setting_dev_desc: 'Enable developer options for plugin development and debugging',
    setting_admin: 'Administrator Options',
    setting_admin_desc: 'Run with administrator privileges for plugin development and debugging',
    setting_cdn: 'Network Acceleration',
    setting_select_dir: 'Select Directory',
    setting_auto_shutdown: 'Automatically shut down after this transfer completes',
    setting_auto_shutdown_desc: 'Effective only for the current task, which includes download and decompression operations',
    setting_auto_test_ipv6: 'IPv6 Network Detection',
    setting_auto_test_ipv6_desc: 'Automatically checks the availability of the IPv6 network upon software startup.',
    home_download: 'Download',
    home_offline_import: 'Offline Dwn',
    home_high_speed_download: 'High Speed',
    home_install: 'Install',
    home_run: 'Launch',
    home_exit: 'exit',
    home_tag_pc: 'PC',
    home_app_title: 'My AI Software',
    support_title: 'QQ: 594691248',
    support_link_title: "Email: a{'@'}chenzhixiong.cn",
    ipv6_dialog_title: 'Friendly Reminder',
    ipv6_dialog_content_1: 'We have detected that your system does not have IPv6 network functionality enabled, which may affect the download speed of projects.',
    ipv6_dialog_content_2: 'Please enable IPv6 network for the best download experience.',
    ipv6_dialog_content_3: 'IPv6 Enablement Guide',
    run_button_cmd_content_1: 'The script has been updated. Please download the latest version from the marketplace to ensure proper project operation.',
    button_ok: 'OK',
    button_donot_remind_again: 'Do Not Remind Again',
    search: "Search",
    market_filter_price: "Price",
    market_filter_price_free: "Free",
    market_filter_price_paid: "Pay",
    market_filter_price_vip: "VIP",
    market_filter_hardware: "Hardware Type",
    market_filter_hardware_cpu: "CPU",
    market_filter_hardware_nvidia: "NVIDIA",
    market_filter_hardware_amd: "AMD",
    market_filter_platform: "Platform",
    market_filter_class: "AI app",
    market_filter_class_image: "Image",
    market_filter_class_sound: "Sound",
    market_filter_class_video: "Video",
    market_filter_class_text: "Text",
    market_filter_tag: "Tags",
    market_filter_model: "Model",
    market_filter_plugin: "Plugin",
    market_filter_workflow: "Workflow",
    market_filter_other: "Other",
    market_filter: "Filter",
    market_filter_reset: "Clear Filter Criteria",
    sort_new: "Newest",
    sort_download: "Downloads",
    sort_like: "Likes",
    sort_favorite: "Favorites",
    app_asce_sort: "Asce",
    app_desc_sort: "Desc",
    service_description: "Service Description",
    service_description_1: "Dear User:",
    service_description_2: "1. Welcome to the AIStarter project management platform! We are dedicated to providing you with a wealth of AI project resources, including large AI models, plugins, workflows, tutorials, and more. All resources on the platform are provided by users (creators) or collected and organized by the platform team from the internet.",
    service_description_3: "2. To ensure efficient resource downloads and a simplified deployment experience, we have introduced VIP services. VIP members can enjoy high-speed downloads and simplified deployment services, enhancing your efficiency and user experience. Additionally, users (creators) and the platform team invest significant time and effort in collecting and organizing projects, especially in simplifying deployment processes and packaging environments based on open-source projects. Therefore, some projects may have a certain fee set at the time of release to compensate for these efforts. We hope that every user can understand and support this approach.",
    service_description_4: "3. Please note that all resources provided on the AIStarter platform are for personal learning and communication purposes only. If you plan to use these resources for commercial purposes, you must purchase official authorized versions to ensure legal and compliant use of the resources. Any unauthorized commercial use violates relevant laws and regulations, and we will not be held responsible for such actions.",
    service_description_5: "Thank you for your understanding and support. Let's work together to maintain a healthy and positive AI technology exchange environment.",
    product_details_author: "Publisher",
    product_details_platform: "Platform",
    product_details_linking: "Related Projects",
    product_details_type1: "Model Type",
    product_details_type2: "Plugin Type",
    product_details_type3: "Workflow Type",
    product_details_device_support: "Device Support",
    product_details_system_requirements: "System Requirements",
    product_details_author_nonesystem: "Author Not Provided",
    product_details_file_size: "File Size",
    product_details_version: "Version",
    product_details_amount: "Price",
    product_details_run_operation: "Run Operation",
    product_details_release_date: "Release Date",
    product_details_update_date: "Update Date",
    product_details_project_description: "Project Description",
    product_details_project_overview: "Project Overview",
    product_details_related_links: "Download Links",
    product_details_related_links_1: "Please log in to view detailed content",
    product_details_related_links_2: "Please subscribe to view detailed content",
    product_details_related_links_3: "Please purchase to view detailed content",
    product_details_related_links_4: "No related information available",
    product_details_vram: "VRAM",
    product_details_add: "Add",
    product_details_buy: "Buy",
    product_details_share: "Share",
    product_details_close: "Close",
    product_details_poster_title: "Download the latest version of AIStarter at:",
    product_details_comments: "Comments",
    poster_download: "Download Poster",
    under_development: "Under development, please explore later",
    not_find_project: "No related information found, please check the marketplace.",
    not_project: "No information found.",
    no_network: "Network connection failed, please check your network",
    project_status_install: "Installed",
    project_status_add: "Added, not installed",
    project_status_unzip: "Pending extraction",
    failed_to_get_details:"Failed to get details! No relevant information available.",
    product_details_not_login_no_buy: "Please login before making a purchase!",
    product_details_vip: "VIP exclusive project, please subscribe before adding!",
    product_details_no_login_no_download: "Please login before downloading!",
    product_details_in_download: "Installing",
    product_details_in_loading: "Loading",
    product_details_no_login_no_add: "Please login before adding!",
    archive_size_calculation_unknown_size: "Unknown size",
  },
  shareproject: {
    titleclass: "Publish Project",
    titlemodel: "Publish Model",
    titleplugin: "Publish Plugin",
    titleworkflow: "Publish Workflow",
    project_icon_text: "Cover Image, Size: 400x300, Format: PNG",
    project_nameclass: "Project Name:",
    project_namemodel: "Model Name:",
    project_nameplugin: "Plugin Name:",
    project_nameworkflow: "Workflow Name:",
    project_name_text: "English, underscores, must be unique, will be used as the installation directory",
    project_versionclass: "Project Version:",
    project_versionmodel: "Model Version:",
    project_versionplugin: "Plugin Version:",
    project_versionworkflow: "Workflow Version:",
    project_hw: "Hardware:",
    project_hw1: "CPU",
    project_hw2: "NV",
    project_hw3: "AMD",
    project_vram: "Graphics:",
    project_vram_text: "Select Minimum GPU Memory Requirement",
    project_price: "Pricing:",
    project_price1: "Free",
    project_price2: "Price",
    project_price3: "VIP",
    project_prices: "Price:",
    project_prices_novip: "NoVIP Price:",
    project_prices_novip_text: "By default, only VIP members can download. After defining a price, non-VIP users will need to purchase according to the price.",
    project_appiconclass: "Application Icon:",
    project_appicon_textclass: "Application Icon: Recommended size 64x64, format: PNG",
    project_appiconmodel: "Model Icon:",
    project_appicon_textmodel: "Model Icon: Recommended size 64x64, format: PNG",
    project_appiconplugin: "Plugin Icon:",
    project_appicon_textplugin: "Plugin Icon: Recommended size 64x64, format: PNG",
    project_appiconworkflow: "Workflow Icon:",
    project_appicon_textworkflow: "Workflow Icon: Recommended size 64x64, format: PNG",
    project_classclass: "Project Type",
    project_classmodel: "Model Type",
    project_classplugin: "Plugin Type",
    project_classworkflow: "Workflow Type",
    project_titleclass: "Project Title:",
    project_titlemodel: "Model Title:",
    project_titleplugin: "Plugin Title:",
    project_titleworkflow: "Workflow Title:",
    project_descclass: "Project Description:",
    project_descmodel: "Model Description:",
    project_descplugin: "Plugin Description:",
    project_descworkflow: "Workflow Description:",
    project_overviewclass: "Project Overview:",
    project_overviewmodel: "Model Overview:",
    project_overviewplugin: "Plugin Overview:",
    project_overviewworkflow: "Workflow Overview:",
    project_url: "Relevant Links:",
    project_clonelink: "Cloud Link:",

    project_button_pack: "Pack",
    project_button_smbit: "Submit",
    project_radio_contentclass: "Skip Project Repackaging",
    project_radio_content_textclass: "Check this to speed up publishing if you've already published the project and only modified application information",
    project_radio_contentmodel: "Skip Model Repackaging",
    project_radio_content_textmodel: "Check this to speed up publishing if you've already published the model and only modified model information",
    project_radio_contentplugin: "Skip Plugin Repackaging",
    project_radio_content_textplugin: "Check this to speed up publishing if you've already published the plugin and only modified plugin information",
    project_radio_contentworkflow: "Skip Workflow Repackaging",
    project_radio_content_textworkflow: "Check this to speed up publishing if you've already published the workflow and only modified workflow information",

    project_packagclass: "Package Project",
    project_packag_textclass: "Package Project Only",
    project_packagmodel: "Package Model",
    project_packag_textmodel: "Package Model Only",
    project_packagplugin: "Package Plugin",
    project_packag_textplugin: "Package Plugin Only",
    project_packagworkflow: "Package Workflow",
    project_packag_textworkflow: "Package Workflow Only",
    project_product_launchclass: "Launch Project",
    project_product_launchmodel: "Launch Model",
    project_product_launchplugin: "Launch Plugin",
    project_product_launchworkflow: "Launch Workflow",
    project_product_launch_text: "Publish to Market",

    project_packag_button: "Package",
    project_repackag_button: "Repackage",

    project_repackag_title: "Repackaging the project requires deleting the original compressed package. Do you want to continue?",
    project_repackag_tit: "Prompt",

    project_del_success: "Deleted successfully",
    project_repackag_check: "Detected modifications in the project, please repackage and share",

    share_success_copy: "Command copied successfully",
  },
  addproject: {
    title: "Add Project",
    project_name1: "AI Project",
    project_name2: "Model",
    project_name3: "Plugin",
    project_name4: "Workflow",
    project_name5: "Other",
    project_onlogin_onadd: "Please log in and then add the project",
    project_onlogin_goguest: "Please log in to view user details",
    project_onlogin_gosendmsg: "Please log in before sending a message",
    project_oncreator_onadd:"Please complete your personal information before adding a project.",

    project_folder: "Project Directory:",
    project_folder_tip: "English, underscores, must be unique, will be used as the installation directory",
    project_folder_pholder: "Located in the 'Products' folder within the installation directory",
    project_version: "Version Number:",
    project_version_pholder: "For example: v1, v1.0, v1.0.0",
    project_related_file: "Project Files",
    project_related_file_tip: "The folder to be compressed and packed.",
    project_related_files: "+ Compress Folder",
    project_type: "Project Type:",
    project_icon: "Application icon:",
    project_title: "Project Title:",
    project_title_pholder: "Title displayed in AI applications and market",
    project_desc: "Project Description:",
    project_desc_pholder: "Basic project information",

    project_edit: "Edit Information",
    project_edit_script: "Create New Script",
    project_test: "Test Run",
    project_publish: "Publish",

    project_appicon_text: "App Icon, Recommended Size: 64x64, Format: PNG",

    project_command_line: "Execution Directory and Command Line",
    project_command_line_title: "Command Execution Directory",
    project_command_line_title_pholder: "Root Directory",

    project_output_form: "Output Form:",
    project_output_form_pholder: "Select Output Information",

    project_output_form_label1: "Standard Output",
    project_output_form_label2: "Error Output",

    project_run_command_line: "Method of Running Command Line:",
    project_run_command_line_pholder: ".\\run.bat or .\\python\\python.exe -u main.py",
    project_run_command_line_pholder2: "For example: .\\clear_cache.bat or .\\python\\python.exe -u web.py",

    project_intg_pkg: "Integration Package Directory",
    project_intg_pkg_pholder: "Please select the root directory of the integration package",

    project_script_mode: "Create Script",
    project_script_mode_ez: "Simple Mode",
    project_script_mode_pro: "Professional Mode",
    project_add_folder: "Add Directory",
    project_folder_name: "Directory Name:",
    project_folder_name_pholder: "For example: Root Directory, Model Directory, etc...",
    project_folder_name_message: "Directory name cannot be empty",
    project_folder_path: "Path:",
    project_folder_path_pholder: "\\aaa\\bbb or \\aaa",
    project_folder_path_message: "Path cannot be empty",

    project_add_folder_button: "Delete",

    project_callback_output: "Callback Output",

    project_run_time: "Startup Success Judgment:",
    project_run_time_pholder: "Example: Enter '1000' for one second. Default is 3 seconds if no end judgment is provided",
    
    project_end_judge: "End Judgment",
    project_end_judge_pholder: "Keywords for successful startup, e.g., Starting",
    
    project_time_and_judge: "Select Callback Output Type",
    project_time_and_judge_value1: "Terminal Output Text",
    project_time_and_judge_value2: "Countdown",

    project_add_project_success: "Project Created Successfully",
    project_add_project_error: "Failed to Create Project",
    project_add_project_exist: "Project Directory Already Exists, Please Change the Directory Name",
    project_add_project_exist_web: "The directory name is already in use, please modify the name",
    project_add_project_exist_server: "Server error, please try again later",
    project_import_integration_package_success: "Integration Package Imported Successfully",
    project_import_integration_package_error: "Failed to Import Integration Package",

    project_existence_title: "Project already exists, please modify the directory name",
    project_needed_script: "Select required scripts",
    project_active_script: "Selected scripts",

    project_advanced_options: "Advanced Options",

    project_onjumpurl: "Non-Automatic Jump URL:",
    project_onjumpurl_pholder: "For example: http://127.0.0.1:7860",

    project_load_prompt: "Loading Prompt:",
    project_load_prompt_pholder: "Default: Starting up, please wait patiently!",

    project_related_settings: "Related Settings",
    project_settings_name: "Setting Name:",
    project_settings_name_pholder: "For example: Startup Options, etc...",
    project_settings_name_message: "Setting name cannot be empty",
    project_settings_type: "Type:",
    project_settings_type_message: "Type cannot be empty",
    project_settings_type_pholder: "Select Type",
    project_settings_type_label1: "Button",
    project_settings_type_label2: "Dropdown",

    project_settings_type_options: "Type Options:",
    project_settings_type_options_message: "Type options cannot be empty",

    project_settings_visible_content: "Visible Content:",
    project_settings_visible_content_pholder: "CPU or GPU, etc...",
    project_settings_visible_content_message: "Visible content cannot be empty",

    project_settings_parameter_values: "Parameter Values:",
    project_settings_parameter_values_pholder: "--cpu or --gpu=0, etc...",
    project_settings_parameter_values_message: "Parameter values cannot be empty",

    project_settings_button_options: "Button Options:",
    project_settings_button_options_label1: "Button Name:",
    project_settings_button_options_label1_pholder: "For example: Click to Clear, etc...",
    project_settings_button_options_label2: "Button Type:",
    project_settings_button_options_label2_1: "Primary",
    project_settings_button_options_label2_2: "Success",
    project_settings_button_options_label2_3: "Info",
    project_settings_button_options_label2_4: "Warning",
    project_settings_button_options_label2_5: "Danger",
    project_settings_button_options_label2_pholder: "Select Button Type",
    project_settings_button_options_label2_message: "Button type cannot be empty",
    project_settings_button_options_message: "Button options cannot be empty",

    project_settings_preview: "Preview:",
    project_settings_preview_tip: "Note: The parameters corresponding to the dropdown option need to be manually added later. (TS: The next step in the script operation should have a direct script operation button)",

    project_title_message: "Please enter the project title",
    project_desc_message: "Please enter the project description",
    project_describe_message: "Please enter project description",
    project_url_message: "Please enter the project related link",
    project_cloudlink_message: "Please enter the cloud storage link",
    project_executecmdfunction_message: "Please enter the execution command",
    project_gupradio_message: "Please select the relevant configuration",
    project_needgupraw_message: "Please select the GPU requirements",
    project_appicon_message: "Please select an application icon",
    project_projectname_message: "Please enter the project directory",
    project_movefile_message: "At least one related file must be entered",
    project_filterclass_message: "Please select an application filter type!",
    project_no: "Project does not exist",
    project_upload_img_error: "Please upload a project image!",
    project_yes: "Project created successfully",
    project_please_error: "Please fill in the correct information!",
    project_name_empty: "Project name cannot be empty!",

    project_name_message: "Directory cannot be empty",
    project_name_message_error: "Directory format is incorrect, only letters, numbers, and underscores are supported",

    project_version_message: "Version number cannot be empty",
    project_version_message_error: "Version number format, e.g., v1 v1.0 v1.0.0",

    project_starttestproject: "Start Testing",
    project_starttestproject_pholder: "The callback of the test application will appear here",
    project_endtestproject: "End Testing",

    project_opentest: "Open Script Debugging",

    project_do_not_publish: "Do Not Publish Application",
    project_do_publish: "Publish Application",

    project_icon_text: "Cover Image Size: 400x300 Format: png",

    project_back: "Back",
    project_next: "Next",
    project_save: "Save",
  },
  login: {
    login_username: "Username:",
    login_email: "Email:",
    login_email_tis: "Please enter a valid email!",
    login_password: "Pwd:",
    login_new_password: "NewPwd:",
    login_confirm_password: "ConfPwd:",
    login_confirm_password_tis: "Passwords do not match.",
    login_code: "Code:",
    login_code_success: "Verification code sent successfully!",
    login_code_error: "Failed to send verification code",
    login_code_error_sending_too_frequently: "Sending verification code too frequently, please try again later!",
    login_code_text: "Get Code",
    login_code_text_wait: "Resend",
    login_forget_password: "Fpwd",
    login_login: "Login",
    login_login_success: "Login Successful!",
    login_login_error: "Login Failed!",
    login_register: "Register",
    login_register_success: "Registration successful!",
    login_register_error: "Registration failed, please try again!",
    login_register_error_email: "Email already registered",
    login_register_error_username: "Username already registered",
    login_user_agreement: "UA",
    login_user_agreement_message: "Please read and agree to the user agreement",
    login_privacy_policy_text: "I have read and agree to",

    login_submit: "Submit",
    login_reset: "Reset",
    login_and_userpassworderror: "Username or password is incorrect",
    login_servererror: "Server error, please try again!",
    login_email_error: "Email verification code is incorrect",
    login_password_vali: "The password must be a string between 6 and 20 characters long, and must include at least one digit, one letter, and one special character.",
    login_username_vali: "Username must be between 3 and 20 characters long and can only contain letters and digits",

    login_format_error: "Please enter the correct format!",
    login_email_null: "Please enter an email",
    login_email_url: "Please enter a valid email address",
    login_code_null: "Please enter the verification code",
    login_password_null: "Please enter a password",
    login_confirm_password_null: "Please enter the confirmation password",
    login_password_min: "Password length must be at least 6 characters",
    login_password_max: "Password length must not exceed 20 characters",

    login_success: "Success",
    login_database_error: "Database error, please try again!",
    login_email_not_exist: "Email is not registered, please register first",
    login_invite_code: "Invite Code:",
    login_invite_code_placeholder: "Enter invite code (optional)",
    login_invite_code_error: "Invalid invite code",
  },
  homeproject: {
    project_move_folderclass: "Directory",
    project_move_foldermodel: "Directory",
    project_move_folderplugin: "Directory",
    project_move_folderworkflow: "Directory",
    project_move_delectclass: "Uninstall",
    project_move_delectmodel: "Uninstall",
    project_move_delectplugin: "Uninstall",
    project_move_delectworkflow: "Uninstall",
    project_move_topclass: "Pin Project",
    project_move_topmodel: "Pin Model",
    project_move_topplugin: "Pin Plugin",
    project_move_topworkflow: "Pin Workflow",
    project_close_top:"Unpin",
    project_top:"TOP",
    project_move_Import: "Import",

    project_move_del_txt: "Are you sure you want to uninstall ",
    project_move_del_txt_2: " ?",
    project_move_del_txt_3: "Prompt",
    project_move_del_txt_4: "Confirm",
    project_move_del_txt_5: "Cancel",

    project_share_editcode: "Edit Code",
    project_share_editcode_save: "Save",
    project_share_editcode_save_ok: "Saved Successfully",
    project_share_editcode_save_error: "Save Failed",
    project_share_run: "Debug Run",
    project_share_run_start: "Start",
    project_share_run_end: "Stop",
    project_share_share: "Share Project",

    project_package_success: "Project packaging succeeded. Please upload the compressed file of the \\Share folder to a third-party cloud storage and fill in the obtained link.",
    project_package_error: "Package failed, please retry",
  },
  versionupd: {
    version_upd_title: "Update Prompt",
    version_upd_button: "Update Now",
    version_upd_tis: "Important Notice: Do not set the software installation directory and project root directory in the same location to avoid accidentally deleting project files during upgrades or uninstallation. Before installation or upgrade, ensure directory paths do not contain Chinese characters or special characters, choose directories with sufficient disk space for file storage, and recommend backing up important data to prevent accidental loss.",
    check_update: "Check Update",
    downloading: "Downloading",
    download_completed: "Download Completed",
    found_new_version: "New version found!",
    already_latest_version: "Already the latest version!",
    check_update_failed: "Check update failed",
    post_download_error: "Error occurred while processing post-download operations",
    download_failed_retry: "Download failed, please retry",
    download_error_retry: "Error occurred during download, please retry",
    download_no_path_warning: "Download completed, but unable to get installation file path",
    install_confirm_title: "Installation Confirmation",
    install_confirm_message: "Download completed! Install new version now?\n\nNote: The application will close during installation",
    install_now: "Install Now",
    install_later: "Install Later",
    starting_installer: "Starting installer, application will close soon...",
    installer_failed: "Failed to start installer, please run the installation file manually",
    native_confirm_message: "Auto installation failed, open file directory for manual installation?",
    auto_install_failed_message: "Auto installation failed, open file directory for manual installation?",
    install_failed_title: "Installation Failed",
    open_directory: "Open Directory",
    download_complete_open_dir_message: "Installation file downloaded, open file directory?",
    download_complete_title: "Download Complete",
    install_operation_error: "Error occurred while processing installation operation",
    download_link_unavailable: "Download link unavailable, please retry later",
     update_content: "Update Content",
     version_number: "🚀 Version",
     download_complete_no_path: "Download completed, but unable to get installation file path",
     install_file_downloaded_message: "Installation file downloaded, open file directory?"
   },
  globaldialog: {
    button_ok: "OK"
  },
  imagetxt: {
    img_class_error: "Please upload a PNG,JPG,JPEG,TIFF format image!",
    img_size_error: "Image size cannot exceed 200KB!",
    img_size_error2: "Image size cannot exceed 500KB!",
    img_size_error3: "Image size cannot exceed 1MB!",
  },
  contextmenu:{
    copy: "Copy",
    paste: "Paste",
    cut: "Cut",
    delete: "Delete",
    select_all: "Select All",
    undo: "Undo",
    redo: "Redo",
    zoom_in: "Zoom In",
    zoom_out: "Zoom Out",
    zoom_reset: "Reset Zoom",
    zoom_fit: "Fit to Screen",
    zoom_fit_width: "Fit to Width",

    copy_success: "Copy successful",
    paste_success: "Paste successful",
    cut_success: "Cut successful",
    delete_success: "Delete successful",
    select_all_success: "Select all successful",
    undo_success: "Undo successful",
    redo_success: "Redo successful",
    zoom_in_success: "Zoom in successful",
    zoom_out_success: "Zoom out successful",
    zoom_reset_success: "Reset zoom successful",
    zoom_fit_success: "Fit to screen successful",

    copy_error: "Copy failed",
    paste_error: "Paste failed",
    cut_error: "Cut failed",
    delete_error: "Delete failed",
    select_all_error: "Select all failed",
    undo_error: "Undo failed",
    redo_error: "Redo failed",
    zoom_in_error: "Zoom in failed",
    zoom_out_error: "Zoom out failed",
    zoom_reset_error: "Reset zoom failed",
  },
  filelist:{
    directory_title: "File Directory Filter",
    directory_search: "Enter keyword",
  },
  myproject:{
    myproject_title: "My Projects",
    myproject_search: "Search Project Name",
    table_id: "ID",
    table_username: "User",
    table_name: "Project Name",
    table_version: "Version",
    table_platform: "Plat",
    table_like: "Likes",
    table_favorite: "Favorites",
    table_download: "Downloads",
    table_review: "Status",
    table_review_success: "Approved",
    table_review_ing: "In Review",
    table_review_error: "Rejected",
    table_operate: "Actions",
    table_operate_look: "View",
    table_operate_del: "Delete",
    table_operate_del_success: "Deleted Successfully",
    table_operate_del_error: "Database Error",
    table_operate_del_tis: "Confirm to delete this project?",
    table_operate_del_title: "Prompt",
    table_operate_del_ok: "Confirm",
    table_operate_del_cancel: "Cancel",
    table_operate_del_cancel_tis: "Cancel Deletion",
    table_operate_edit: "Edit",
    table_operate_edit_error: "Plugin not found, please add it before editing",
    table_operate_edit_tis: "Confirm to edit this project?",
    table_operate_edit_title: "Prompt",
    table_operate_edit_ok: "Confirm",
    table_operate_edit_cancel: "Cancel",
    form_project_query: "Project Query",
    form_platform_query: "Platform Query",
    form_platform_query_placeholder: "Platform Query",
    form_review_status: "Review Status",
    form_review_status_placeholder: "Review Status",
    form_query_button: "Query",
    form_reset_button: "Reset",
  },
  myresources:{
    myresources_title: "My Resources",
    form_resource_query: "Resource Query",
    form_platform_query: "Platform Query",
    form_platform_query_placeholder: "Platform Query",
    form_resource_type: "Resource Type",
    form_resource_type_placeholder: "Resource Type",
    form_review_status: "Review Status",
    form_review_status_placeholder: "Review Status",
    form_query_button: "Query",
    form_reset_button: "Reset",
    resource_type_model: "Model",
    resource_type_plugin: "Plugin",
    resource_type_workflow: "Workflow",
    resource_type_other: "Other",
  },
  myfavorites:{
    myfavorites_title: "My Favorites",
    form_project_query: "Project Query",
    form_project_type: "Project Type",
    form_project_type_placeholder: "Project Type",
    form_query_button: "Query",
    form_reset_button: "Reset",
    table_project_type: "Project Type",
    table_operate_unfavorite: "Unfavorite",
    project_type_app: "App",
    project_type_model: "Model",
    project_type_plugin: "Plugin",
    project_type_workflow: "Workflow",
    unfavorite_confirm: "Confirm to unfavorite?",
  },
  mydevice:{
    mydevice_title: "My Devices",
    device_current: "Current",
    device_delete: "Delete",
    delete_success: "Delete successful",
  },
  mydownload:{
    mydownload_title: "My Downloads",
    form_project_query: "Project Query",
    form_project_type: "Project Type",
    form_project_type_placeholder: "Project Type",
    form_start_time: "Start Time",
    form_end_time: "End Time",
    form_query_button: "Query",
    form_reset_button: "Reset",
    table_project_type: "Project Type",
    table_download_count: "Download Count",
    table_download_time: "Download Time",
    project_type_app: "App",
    project_type_model: "Model",
    project_type_plugin: "Plugin",
    project_type_workflow: "Workflow",
    delete_confirm: "Confirm to delete this download record?",
  },
  mybuy: {
    mybuy_title: "Purchase Records",
    form_date_label: "Date",
    date_placeholder: "Pick a day",
    table_date: "Date",
    table_order_no: "Order No",
    table_merchant: "Merchant",
    table_title: "Title",
    table_type: "Type",
    merchant_platform: "Platform",
    filter_vip: "VIP",
    filter_ai_app: "AI App",
    filter_ai_model: "AI Model",
    filter_ai_plugin: "AI Plugin",
    filter_ai_workflow: "AI Workflow",
    filter_creator_renewal: "Creator Renewal",
    channel_vip: "vip",
    channel_ai_project: "AI Project",
    channel_ai_model: "AI Model",
    channel_ai_plugin: "AI Plugin",
    channel_ai_workflow: "AI Workflow",
    channel_creator_renewal: "Creator Renewal"
  },
  mywallet: {
    wallet_title: "My Balance",
    balance_label: "Balance",
    withdraw_button: "Withdraw",
    under_review_balance: "Balance Under Review",
    under_review_tooltip_title: "What is Balance Under Review",
    under_review_tooltip_content: "When creators' earnings are converted to balance, there may be a review process. Balance under review cannot be withdrawn temporarily",
    withdraw_date_reminder: "Withdrawal Date Reminder",
    withdraw_rule_title: "Withdrawal Rules",
    withdraw_rule_content: "The 1st-10th of each month is the application period for withdrawals. Payments will be completed before the 20th of the current month after approval.",
    withdraw_details_title: "Withdrawal Details",
    recent_date_label: "Recent Date",
    date_placeholder: "Pick a day",
    table_transfer_time: "Withdrawal Time",
    table_order_number: "Order No",
    table_status: "Status",
    table_tax_amount: "Tax Amount",
    table_transfer_balance: "Withdrawal Amount",
    table_transfer_channel: "Withdrawal Channel",
    table_remark: "Remark",
    remark_view: "View",
    remark_none: "None",
    channel_alipay: "Alipay",
    channel_wechat: "WeChat",
    channel_paypal: "PayPal",
    channel_bank: "Bank Card",
    channel_enterprise: "Enterprise Account",
    status_pending: "Pending Review",
    status_approved: "Approved",
    status_transferring: "Transferring",
    status_completed: "Completed",
    status_rejected: "Rejected",
    status_cancelled: "Cancelled",
    status_unknown: "Unknown Status",
    withdraw_min_amount_error: "Withdrawal amount cannot be less than 100"
  },
  header:{
    create_project: "Publish Work",
    subscribe: "Subscribe",
    join_member: "Become a Member",
    vip_annual_member: "VIP (Annual Membership)",
    vip_lifetime_member: "VIP (Lifetime Membership)",
    login: "Login",
    join_creator: "Apply to Become a Creator",
    my_account: "My Account",
    logout: "Logout",
    renew: 'Renew',
  },
  modelproject: {
      project_folder: "Model Directory:",
      project_folder_tip: "English, underscores, must be unique, will be used as the installation directory",
      project_folder_pholder: "Located in the 'Models' folder of the installation directory",
      project_version: "Version Number:",
      project_version_pholder: "For example: v1 v1.0 v1.0.0",
      project_icon: "Model Icon:",
      project_appicon_text: "Model icon recommended size: 64x64 format: png",
      project_type: "Model Type:",
      project_title: "Model Title:",
      project_title_pholder: "Title displayed in the model and market",
      project_desc: "Model Description:",
      project_desc_pholder: "Basic information about the model",
      project_intg_pkg: "Import Model:",
      project_intg_pkg_pholder: "Please select the root directory of the model",
      project_existence_title: "Project already exists, please modify the directory name",
      project_title_message: "Please enter the model title",
      project_desc_message: "Please enter the model description"
  },
  pluginproject: {
      project_folder: "Plugin Directory:",
      project_folder_tip: "English, underscores, must be unique, will be used as the installation directory",
      project_folder_pholder: "Located in the 'Plugins' folder of the installation directory",
      project_version: "Version Number:",
      project_version_pholder: "For example: v1 v1.0 v1.0.0",
      project_icon: "Plugin Icon:",
      project_appicon_text: "Plugin icon recommended size: 64x64 format: png",
      project_type: "Plugin Type:",
      project_title: "Plugin Title:",
      project_title_pholder: "Title displayed in the plugin and market",
      project_desc: "Plugin Description:",
      project_desc_pholder: "Basic information about the plugin",
      project_intg_pkg: "Import Plugin:",
      project_intg_pkg_pholder: "Please select the root directory of the plugin",
      project_existence_title: "Project already exists, please modify the directory name",
      project_title_message: "Please enter the plugin title",
      project_desc_message: "Please enter the plugin description"
  },
  workflowproject: {
      project_folder: "Workflow Directory:",
      project_folder_tip: "English, underscores, must be unique, will be used as the installation directory",
      project_folder_pholder: "Located in the 'Workflows' folder of the installation directory",
      project_version: "Version Number:",
      project_version_pholder: "For example: v1 v1.0 v1.0.0",
      project_icon: "Workflow Icon:",
      project_appicon_text: "Workflow icon recommended size: 64x64 format: png",
      project_type: "Workflow Type:",
      project_title: "Workflow Title:",
      project_title_pholder: "Title displayed in the workflow and market",
      project_desc: "Workflow Description:",
      project_desc_pholder: "Basic information about the workflow",
      project_intg_pkg: "Import Workflow:",
      project_intg_pkg_pholder: "Please select the root directory of the workflow",
      project_existence_title: "Project already exists, please modify the directory name",
      project_title_message: "Please enter the workflow title",
      project_desc_message: "Please enter the workflow description"
  },
  personalcenter: {
      updatapwd: "Update Password",
      oldpwd: "Old Password",
      newpwd: "New Password",
      confirmpwd: "Confirm Password",
      submit: "Submit",
      login_password_vali: "Password must be a string of 6 to 20 characters, containing at least one number and one letter.",
      confirm_password_vali: "Password and confirm password do not match.",
      update_success: "Password updated successfully.",
      oldpwd_error: "Incorrect old password.",
      update_error: "Failed to update password.",
      myaccount: 'User Center',
      mymessage: 'Messages',
      comment_message: 'Comments',
      like_message: 'Likes',
      myorder: 'Orders',
      mywallet: 'Wallet',
      myincome: 'Income',
      mydiscounts: 'Discounts',
      userinfo: 'User Info',
      userinfo_update: 'Edit',
      userinfo_updateinfo: 'Complete',
      userinfo_updatepwd: 'Password',
      myproject: 'Projects',
      myproject_my: 'Projects',
      myresources_my:'Resources',
      myfavorites: 'Favorites',
      myhistory: 'History',
      mydownload: 'Downloads',
      myorderhistory: 'Purchases',
      collection: 'Collection',
      download: 'Download',
      likes: 'Likes',
      income: 'Total Revenue',
      balance: 'Wallet',
      expire: 'Expiration',
      name: 'Name:',
      idcard: 'ID Card:',
      idcardexpire: 'ID Card Expiration Date:',
      data: 'Date',
      positiveidcardimgupload: "Front and Back of ID Card:",
      positiveidcard: "Front of ID Card",
      negativeidcard: "Back of ID Card",
      wechatimage:"WeChat QR Code",
      alipayimage:"Alipay QR Code",
      residence: 'Residence:',
      placeholderresidence: "Please select your residence",
      wechat: 'WeChat:',
      alipay: 'Alipay:',
      bankcard: 'Bank Account:',
      bankname: 'Bank Name:',
      save: 'Submit',
      complete_personal_info: 'Complete Personal Information',
      toggle_sensitive_info: 'Hide/Show Sensitive Information',
      hidden_info: '*** Hidden Information ***',
      image_hidden: '*** Image Hidden ***',
      password_verification: 'Password Verification',
      enter_login_password: 'Please enter your login password',
      password_placeholder: 'Please enter password',
      password_verification_failed: 'Password verification failed',
      password_cannot_be_empty: 'Password cannot be empty',
      password_verification_success: 'Password verification successful',
      password_verification_error: 'Password verification error',
      hide_sensitive_info: 'Hide Sensitive Info',
      show_sensitive_info: 'Show Sensitive Info',
      enter_password_prompt: 'Please enter password to verify identity',
      password_required: 'Please enter password',
      password_verify_success: 'Password verification successful',
      password_error: 'Password error',
      password_input_cancelled: 'Password input cancelled',
      password_verify_failed: 'Password verification failed',
      enterprise_certification: 'Enterprise',
  },
  resconfig:{
    home_resconfig_button: 'Configure',
    resconfig_title: 'Project Name:',
    resconfig_title_vali: 'Please enter project name',
    resconfig_table_name: 'Project Name',
    resconfig_ok: 'Configure',
    resconfig_custom_linking: 'Custom Association',
    resconfig_model: 'Model',
    resconfig_plugin: 'Plugin',
    resconfig_workflow: 'Workflow',
    resconfig_configok: 'Successfully configured to project',
    resconfig_configno: 'Configuration cancelled',
    resconfig_nodisk:'Please select folders under the same disk drive',
  },
  subcenter:{
    time_limited_discount:'Time-Limited Discount',
    time_limited:'T.L.',
    yuan:'Yuan',
    list_price:'L.P.',
    loyalty_program:'Membership Plan',
    please_login:'Please Login First',
    please_wait:'Requesting Data, Please Wait!',
    please_wait_no:'Failed to Get Data!',
    cell_me_phone:'Phone',
    cell_me_email:'Email',
    cell_me:'Contact Us',
    cell_me_confirm:'Confirm',
  },
  qrcodepaymentdialog:{
    price: 'Price: ',
    qrcodeexpire: 'QR code has expired, ',
    paypalexpire: 'PayPal has expired, ',
    balance_expire: 'Balance payment has expired',
    refresh: 'Refresh',
    protocol: 'Please read and agree to the subscription agreement',
    qrcodegenerate: 'Generating, please wait...',
    paypalpayment: 'Pay with PayPal',
    balancepayment: 'Please pay with balance',
    account_balance: 'Account Balance',
    pay_now: 'Pay Now',
    subscription_protocol: 'I have read and agree to the',
    subscription_protocol_link: 'Subscription Agreement',
    discount_placeholder: 'Please enter discount code',
    discount: 'Use discount code',
    backtoseller: 'Back to merchant',
    wechatpayment: 'Please scan with WeChat to pay',
    alipaypayment: 'Please scan with Alipay to pay',
    paypalpayments: 'Please pay with PayPal',
    stripepayment: 'Please pay with Stripe',
    stripepayments: 'Pay with Stripe',
    pingpongpayment: 'Please pay with PingPong',
    pingpongpayments: 'Pay with PingPong',
    createorder: 'Creating order...',
    createordererror: 'Failed to create order, please try again later!',
    payment_success: 'Payment successful!',
    couponcodeempty:'Coupon code cannot be empty!',
    password_confirmation_title: 'Payment Password Confirmation',
    payment_amount: 'Payment Amount',
    payment_password_placeholder: 'Please enter payment password',
    password_required: 'Please enter payment password',
    insufficient_balance: 'Insufficient balance',
    cancel: 'Cancel',
    confirm_payment: 'Confirm Payment',
  },
  guestpage: {
    not_set: 'Not Set',
    annual_member: 'Annual Member',
    permanent_member: 'Permanent Member',
    regular_member: 'Regular Member',
    send_message: 'Send Msg',
    none: 'None',
    back_to_personal_center: 'Click to return to personal center',
    representative_works: 'Representative Works',
    category_resources: 'Category Resources',
    homepage: 'Home',
    likes: 'Likes',
    favorites: 'Favorites'
  },
  mypage: {
    not_set: 'Not Set',
    none: 'None',
    creator: 'Creator',
    my_devices: 'Devices'
  },
  myupdateinfo: {
    not_submitted: 'Not Submitted',
    under_review: 'Under Review',
    not_approved: 'Not Approved',
    approved: 'Approved',
    id_card_required: 'Please enter ID number',
    id_card_length: 'ID number length should be 6-30 characters',
    id_card_format: 'ID number can only contain letters, numbers and hyphens',
    name_required: 'Please enter name',
    name_length: 'Name length should be 2-20 characters',
    id_card_expire_required: 'Please enter ID expiry date',
    paypal_format: 'Please enter a valid PayPal account (email)',
    paypal_length: 'PayPal account length should be 5-50 characters',
    bank_card_required: 'Please enter bank card number',
    bank_card_format: 'Bank card number should be 8-34 letters, numbers or spaces',
    bank_name_required: 'Please enter bank name',
    bank_name_length: 'Length should be 2-50 characters',
    bank_name_format: 'Only Chinese, English, numbers and spaces are supported',
    address_length: 'Address length should be 5-100 characters',
    modify_success: 'Modified successfully',
    payment_method_required: 'Please fill in at least one payment method',
    bank_info_required: 'Please fill in bank card number and bank name',
    id_card_photos_required: 'Please upload ID card photos',
    id_card_back_required: 'Please also upload the back of ID card',
    id_card_front_required: 'Please also upload the front of ID card',
    form_validation_failed: 'Form validation failed'
  },
  myupdate: {
    modify_personal_info: 'Modify Personal Information',
    avatar: 'Avatar',
    alias_chinese_name: 'Alias (Chinese Name)',
    your_chinese_name: 'Your Chinese Name',
    email: 'Email',
    your_email: 'Your Email',
    phone_number: 'Phone Number',
    your_phone_number: 'Your Phone Number',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    secret: 'Secret',
    bio: 'Bio',
    set_your_signature: 'Set your signature- ( ゜- ゜)つロ',
    modify: 'Modify',
    cancel: 'Cancel',
    upload_png_format: 'Please upload PNG format image!',
    image_size_limit: 'Image size cannot exceed 200KB!',
    phone_required: 'Please enter phone number',
    phone_format: 'Please enter a valid international phone number (e.g. +8613812345678)',
    alias_required: 'Please enter alias',
    alias_length: 'Alias length should be 2-20 characters',
    bio_length: 'Bio should not exceed 100 characters',
    modify_success: 'Modified successfully!'
  },
  mymessage: {
    message_center: 'Message Center',
    connected: 'Connected',
    connecting: 'Connecting...',
    reconnect: 'Reconnect',
    refresh: 'Refresh',
    search_contacts: 'Search contacts...',
    no_messages: 'No messages',
    load_more_contacts: 'Load more contacts',
    online: 'Online',
    offline: 'Offline',
    enter_personal_page: 'Visit their profile',
    send_message_hint: '💡 Press Ctrl+Enter to send message',
    select_contact_to_chat: 'Select a contact to start chatting',
    select_contact_description: 'Choose a contact from the left list to start a conversation',
    message_settings: 'Message Settings',
    message_notifications: 'Message Notifications',
    sound_notifications: 'Sound Notifications',
    auto_reply: 'Auto Reply',
    auto_reply_placeholder: 'Set auto reply message',
    cancel: 'Cancel',
    save: 'Save',
    chat_connection_failed: 'Chat connection failed, please check network connection',
    chat_connection_error: 'Error occurred while establishing chat connection',
    select_contact_first: 'Please select a contact first',
    connection_not_established: 'Chat connection not established, please try again later',
    message_content_empty: 'Message content cannot be empty',
    send_message_failed: 'Failed to send message',
    unknown_error: 'Unknown error',
    messages_refreshed: 'Messages refreshed',
    refresh_failed: 'Refresh failed',
    cache_cleared: 'Cache cleared',
    clear_cache_failed: 'Failed to clear cache',
    expired_cache_cleared: 'Expired cache cleared',
    clear_expired_cache_failed: 'Failed to clear expired cache',
    settings_saved: 'Settings saved',
    just_now: 'Now',
    minutes_ago: 'm ago',
    hours_ago: 'h ago',
    days_ago: 'd ago',
    delete_contact: 'Delete Contact',
    delete_contact_title: 'Delete Contact',
    delete_contact_confirm: 'Are you sure you want to delete contact {name}? This will clear all chat history.',
    confirm: 'Confirm',
    contact_deleted: 'Contact deleted',
    delete_contact_failed: 'Failed to delete contact',
    settings: 'Settings',
    clear_cache: 'Clear Cache',
    clear_all_cache: 'Clear All Cache',
    clear_expired_cache: 'Clear Expired Cache'
  },
  mycommentmessage: {
    project: 'Project',
    original_content: 'Original Content',
    loading: 'Loading...',
    scroll_load_more: 'Scroll to load more',
    no_more_data: 'No more data',
    no_comment_messages: 'No comment messages',
    just_now: 'Just now',
    minutes_ago: '{minutes} minutes ago',
    hours_ago: '{hours} hours ago',
    days_ago: '{days} days ago',
    marked_as_read: 'Marked as read',
    mark_failed: 'Mark failed',
    load_failed: 'Failed to load comment messages'
  },
  mylikemessage: {
    liked_your: 'liked your',
    project: 'Project',
    comment: 'comment',
    project_content: 'project',
    image: 'image',
    post: 'post',
    content: 'content',
    loading: 'Loading...',
    scroll_load_more: 'Scroll to load more',
    no_more_data: 'No more data',
    no_like_messages: 'No like messages',
    just_now: 'Just now',
    minutes_ago: '{minutes} minutes ago',
    hours_ago: '{hours} hours ago',
    days_ago: '{days} days ago',
    marked_as_read: 'Marked as read',
    mark_failed: 'Mark failed',
    load_failed: 'Failed to load like messages'
  },
  myincome: {
    yesterday_income: 'Yesterday Income',
    thirty_days_income: 'Last 30 Days Income',
    three_months_income: 'Last 3 Months Income',
    income_details: 'Income Details',
    time_label: 'Time',
    date_placeholder: 'Pick a day',
    table_date: 'Date',
    table_total: 'Total',
    table_reward_amount: 'Reward Amount',
    table_creation_income: 'Creation Income',
    table_refund: 'Refund',
    table_order_desc: 'Remark'
  },
  mydiscounts: {
    my_coupons: 'My Coupons',
    coupon_count_unit: 'pcs',
    request_more: 'Request More',
    used_coupons: 'Used Coupons',
    applying_coupons: 'Applying Coupons',
    application_list: 'Application List',
    time_label: 'Time',
    date_placeholder: 'Pick a day',
    table_apply_time: 'Apply Time',
    table_applicant: 'Applicant',
    table_apply_count: 'Apply Count',
    table_issued_count: 'Issued Count',
    table_review_status: 'Review Status',
    table_remark: 'Remark',
    table_reviewer: 'Reviewer',
    table_review_time: 'Review Time',
    my_discount_codes: 'My Discount Codes',
    table_discount_code: 'Discount Code',
    table_cashback_amount: 'Referral Reward',
    table_valid_from: 'Valid From',
    table_valid_to: 'Valid To',
    table_status: 'Status',
    table_user: 'User',
    table_actions: 'Actions',
    filter_unused: 'Unused',
    filter_used: 'Used',
    filter_expired: 'Expired',
    button_copy: 'Copy',
    button_copy_link: 'Copy Link',
    button_batch_export: 'Batch Export',
    copy_success: 'Copy Success',
    export_confirm_title: 'Export Coupons',
    export_confirm_message: 'Are you sure you want to export?',
    export_confirm_button: 'Confirm',
    export_cancel_button: 'Cancel',
    export_success: 'Exported',
    export_filename: 'discount_codes_export.xlsx',
    export_sheet_name: 'Discount Codes',
    export_headers: {
      serial_number: 'Serial Number',
      discount_code: 'Discount Code',
      min_amount: 'Min Amount',
      cashback_amount: 'Cashback Amount',
      valid_from: 'Valid From',
      valid_to: 'Valid To',
      usage_status: 'Usage Status',
      user: 'User',
      share_link: 'Share Link'
    },
    request_more_title: 'Request Coupons',
    request_more_message: 'Enter the quantity you want to apply for (Note: The actual issued quantity may be less than the applied quantity)',
    request_more_button: 'Apply',
    request_more_error: 'Only numbers allowed',
    status_pending: 'Pending',
    status_approved: 'Approved',
    status_rejected: 'Rejected',
    coupon_unused: 'Unused',
    coupon_used: 'Used',
    coupon_expired: 'Expired',
    currency_unit: '',
    apply_success: 'Coupon application submitted, please wait for review'
  },
  myinvite: {
    my_invite_code: 'My Invite Code',
    share_invite_description: 'Share this invite code with friends to earn promotion rewards.',
    copy_link: 'Copy Link',
    generate_invite_code: 'Click to automatically generate your invite code',
    custom_invite_code: 'Custom Generate Invite Code',
    parent_bound_cannot_unbind: 'Inviter is bound and cannot be unbound',
    bind_inviter_placeholder: 'Bind Inviter',
    bind_button: 'Bind',
    bind_warning: 'Cannot unbind after binding, please operate carefully',
    my_invited_count: 'My Invited Users',
    promotion_earnings: 'Promotion Earnings',
    promotion_commission: 'Promotion Commission',
    order_count: 'Order Count',
    invite_code_generated: 'Invite code generated successfully!',
    generate_failed: 'Failed to generate invite code',
    generate_failed_retry: 'Failed to generate invite code, please try again later',
    invite_code_copied: 'Invite code copied to clipboard',
    please_enter_invite_code: 'Please enter invite code',
    bind_confirm_title: 'Confirm Binding',
    bind_confirm_message: 'Cannot unbind after binding inviter, are you sure to bind?',
    confirm_bind: 'Confirm Bind',
    cancel: 'Cancel',
    confirm: 'Confirm',
    bind_success: 'Parent invite code bound successfully!',
    bind_failed: 'Binding failed',
    bind_failed_retry: 'Binding failed, please try again later',
    get_invite_info_failed: 'Failed to get invite information',
    custom_invite_title: 'Custom Invite Code',
    custom_invite_prompt: 'Please enter your custom invite code (6-20 characters, letters and numbers only)',
    custom_invite_placeholder: 'Enter custom invite code',
    custom_invite_format_error: 'Invite code must be 6-20 characters, letters and numbers only',
    custom_invite_success: 'Custom invite code set successfully!',
    custom_invite_failed: 'Failed to set custom invite code',
    custom_invite_failed_retry: 'Failed to set custom invite code, please try again later'
  },
  myinvitemenu: {
    my_invite: 'Invitations'
  },
  withdrawdialog: {
    dialog_title: 'User Withdrawal',
    amount_label: 'Withdrawal Amount',
    amount_placeholder: 'Please enter amount',
    method_label: 'Withdrawal Method',
    method_placeholder: 'Please select',
    cancel_button: 'Cancel',
    confirm_button: 'Confirm',
    withdraw_types: {
      wechat: 'WeChat',
      alipay: 'Alipay',
      bank: 'Bank Card',
      paypal: 'PayPal',
      enterprise: 'Enterprise Account'
    },
    validation: {
      amount_required: 'Please enter amount',
      amount_must_be_number: 'Amount must be a number',
      amount_range: 'Amount must be between {min}~{max}',
      amount_decimal: 'Maximum 2 decimal places',
      method_required: 'Please select withdrawal method'
    },
    messages: {
      min_amount_error: 'Minimum withdrawal amount is {min}',
      max_amount_error: 'Maximum withdrawal amount is {max}',
      success_message: 'Withdrawal application successful, amount ¥{amount}, expected to arrive within 1-3 business days, please wait patiently for review.'
    }
  },
  userbandialog: {
    dialog_title: 'You have been banned from using AIStarter',
    ban_time_prefix: 'Ban time: ',
    ban_time_permanent: 'Permanent ban',
    ban_reason: 'For specific reasons, please contact customer service',
    confirm_button: 'Got it'
  },
  devicedialog: {
    dialog_title: 'Computer login device limit exceeded, please log out device first',
    dialog_subtitle: 'This account has been logged in on other computers, you can log out logged-in devices or log in with a new account',
    my_devices: 'My Devices',
    current_device: 'Current',
    delete_button: 'Delete',
    device_management_title: 'Device Management Instructions',
    device_management_rules: {
      rule1: '• Each account can only modify device information 3 times per year, please operate with caution',
      rule2: '• After deleting the current device, the software will exit immediately and automatically log out the account',
      rule3: '• After closing this window, the system will automatically log out the current account',
      rule4: 'Note: After deleting the device, you will not be able to use this device to log in, please confirm before operating'
    },
    contact_service: 'Contact Customer Service',
    wechat_scan_alt: 'WeChat Scan',
    copy_success: 'Copy successful',
    copy_log: 'Copied: ',
    delete_confirm_message: 'Are you sure to delete [{deviceName}] device?',
    delete_confirm_title: 'Tip',
    delete_confirm_button: 'Confirm',
    delete_cancel_button: 'Cancel',
    delete_success: 'Delete successful'
  },
  productdetailsdialog: {
    send_message: 'Send Msg',
    login_required_comments: 'Please log in to view comments',
    subscribe_required_comments: 'Please subscribe to view comments',
    purchase_required_comments: 'Please purchase to view comments',
    login_required_first: 'Please log in first',
    favorite_failed: 'Failed to favorite, please try again later',
    like_failed: 'Failed to like, please try again later',
    copy_text: 'Copy',
    copy_selected_text: 'Copy selected text',
    network_error_message: 'Network error, failed to send private message'
  },
  commentcomp: {
    like: 'Like',
    favorite: 'Favorite',
    download: 'Download',
    send_message: 'Send Msg',
    get_user_info_failed: 'Failed to get user info',
    get_comments_failed: 'Failed to get comments',
    network_error_get_comments: 'Network error, failed to get comments',
    network_error_send_message: 'Network error, failed to send private message',
    comment_success: 'Comment successful!',
    comment_failed: 'Comment failed',
    network_error_comment: 'Network error, comment failed',
    operation_failed: 'Operation failed',
    network_error_operation: 'Network error, operation failed',
    get_reply_failed: 'Failed to get reply',
    network_error_get_reply: 'Network error, failed to get reply',
    delete_success: 'Delete successful',
    delete_failed: 'Delete failed',
    network_error_delete: 'Network error, delete failed',
    image_size_limit: 'Image size cannot exceed 1MB, current file size: ',
    image_format_error: 'Only PNG format images are supported, current file type: ',
    image_process_failed: 'Image processing failed',
    upload_failed: 'Upload failed',
    image_upload_failed: 'Image upload failed'
  },
  operate: {
    report: 'Report',
    delete: 'Delete',
    copy: 'Copy',
    report_comment: 'Report Comment',
    report_reason: 'Report Rsn',
    select_report_reason: 'Please select a report reason',
    spam_ads: 'Spam Ads',
    malicious_attack: 'Malicious Attack',
    pornographic_content: 'Pornographic Content',
    political_sensitive: 'Political Sensitive',
    other: 'Other',
    detailed_description: 'Detail Desc',
    describe_report_reason: 'Please describe the report reason in detail...',
    cancel: 'Cancel',
    submit_report: 'Submit Report',
    fill_complete_info: 'Please fill in complete report information',
    report_success: 'Report successful',
    report_failed: 'Report failed',
    network_error_report: 'Network error, report failed',
    no_permission_delete: 'You do not have permission to delete this comment',
    copy_success: 'Copy successful'
  },
  common: {
    confirm: 'Confirm',
    cancel: 'Cancel',
    close: 'Close'
  },
  enterprise: {
    create_enterprise: 'Create Enterprise',
    create_enterprise_cert: 'Create Enterprise Certification',
    create_enterprise_desc: 'Create a new enterprise organization',
    join_enterprise: 'Join Enterprise',
    join_enterprise_desc: 'Join an existing enterprise using enterprise code',
    enterprise_info: 'Enterprise Information',
    enterprise_name: 'Enterprise Name',
    enterprise_code: 'Enterprise Code',
    enterprise_desc: 'Enterprise Description',
    credit_code: 'Unified Social Credit Code',
    legal_person_name: 'Legal Person Name',
    business_license: 'Business License',
    id_card_front: 'ID Card Front',
    id_card_back: 'ID Card Back',
    member_count: 'Member Count',
    join_date: 'Join Date',
    leave_enterprise: 'Leave Enterprise',
    enter_enterprise_name: 'Please enter enterprise name',
    enter_enterprise_desc: 'Please enter enterprise description',
    enter_description: 'Please enter description',
    enter_enterprise_code: 'Please enter enterprise code',
    enter_credit_code: 'Please enter unified social credit code',
    enter_legal_person_name: 'Please enter legal person name',
    upload_business_license: 'Upload Business License',
    upload_id_card_front: 'Upload ID Card Front',
    upload_id_card_back: 'Upload ID Card Back',
    create: 'Create',
    join: 'Join',
    name_required: 'Enterprise name is required',
    name_length: 'Enterprise name should be 2-50 characters long',
    desc_length: 'Enterprise description cannot exceed 200 characters',
    code_required: 'Enterprise code is required',
    code_length: 'Enterprise code should be 6-20 characters long',
    credit_code_required: 'Unified social credit code is required',
    credit_code_format: 'Invalid unified social credit code format',
    legal_person_required: 'Legal person name is required',
    legal_person_length: 'Legal person name should be 2-20 characters long',
    business_license_required: 'Please upload business license',
    id_card_front_required: 'Please upload ID card front',
    id_card_back_required: 'Please upload ID card back',
    create_success: 'Enterprise created successfully',
    create_failed: 'Failed to create enterprise',
    join_success: 'Joined enterprise successfully',
    join_failed: 'Failed to join enterprise',
    leave_confirm: 'Are you sure you want to leave the current enterprise? You will lose access to enterprise resources after leaving.',
    leave_success: 'Left enterprise successfully',
    leave_failed: 'Failed to leave enterprise',
    status_pending: 'Pending',
    status_approved: 'Approved',
    status_rejected: 'Rejected',
    edit_info: 'Edit Info',
    edit_enterprise_info: 'Edit Enterprise Info',
    submit_date: 'Submit Date',
    audit_date: 'Audit Date',
    reject_reason: 'Reject Reason',
    update: 'Update',
    enter_bank_card: 'Please enter bank card number',
    enter_bank_name: 'Please enter bank name',
    cancel_association: 'Cancel Association',
    associate_cert: 'Associate Certification',
    associate: 'Associate',
    update_enterprise_info: 'Update Enterprise Info',
    exit_under_review: 'Exit Application Under Review',
    exit_application_reviewing: 'Exit Application is Under Review',
    exit_review_message: 'Your exit application is under review, please wait patiently',
    contact_admin_or_support: 'Please contact administrator or support',
    create_cert_failed: 'Failed to create certification',
    join_failed_retry: 'Failed to join enterprise, please try again later',
    enter_exit_reason: 'Please enter exit reason',
    exit_enterprise: 'Exit Enterprise',
    confirm_exit: 'Confirm Exit',
    enter_exit_reason_placeholder: 'Please enter exit reason (optional)',
    exit_application_submitted: 'Exit application submitted',
    exit_failed: 'Exit application failed',
    exit_failed_retry: 'Exit application failed, please try again later',
    update_success: 'Enterprise information updated successfully',
    update_failed: 'Failed to update enterprise information',
    code_copied: 'Enterprise code copied to clipboard',
    join_under_review: 'Join Application Under Review',
    join_application_reviewing: 'Join Application is Under Review',
    join_review_message: 'Your join application is under review, please wait patiently for administrator approval'
  }
};
