export default {
  app: {
    title: 'AI Starter',
    title_no_admin:'以非管理员身份运行',
    title_admin: '以管理员身份运行',
    tis_place_admin: '请以管理员身份运行',
    menu_home: '首页',
    menu_file: '文件',
    menu_ai_navigation: 'AI导航',
    menu_discus: '交流',
    menu_setting: '设置',
    menu_support: '支持',
    customer_service: '客服',
    menu_light: '灯泡',
    menu_market: '市场',
    menu_terminal: "终端",
    menu_review: '审核',
    menu_my: '我的',
    setting_project_dir: '设置项目根目录',
    setting_project_dir_tis: '请选择不含中文或特殊字符的目录存放项目文件。不要将软件安装目录与项目根目录设在同一位置，以防升级或卸载时删除已安装的项目。建议选择空间充足的磁盘。',
    setting_project_dir_select: '选择目录',
    setting_preferences_title: '首选项',
    setting_lang: '语言设置',
    setting_dir: '项目根目录',
    setting_dev: '开发者选项',
    setting_dev_desc: '打开开发者选项，用于插件开发调试',
    setting_admin: '管理员选项',
    setting_admin_desc: '以管理员权限运行，用于插件开发调试',
    setting_cdn: '网络加速',
    setting_select_dir: '选择目录',
    setting_auto_shutdown: '本次传输完成自动关机',
    setting_auto_shutdown_desc: '仅本次任务生效，传输任务包含下载、解压',
    setting_auto_test_ipv6: 'IPv6网络检测',
    setting_auto_test_ipv6_desc: '软件启动后检测IPv6网络是否可用',
    home_download: '普通下载',
    home_offline_import:'离线下载',
    home_high_speed_download: '高速下载',
    home_install: '安装',
    home_run: '启动',
    home_exit: '结束',
    home_tag_pc: '桌面',
    home_app_title: '我的AI应用',
    support_title: 'QQ: 594691248',
    support_link_title: "邮箱: a{'@'}chenzhixiong.cn",
    ipv6_dialog_title: '温馨提示',
    ipv6_dialog_content_1: '检测到您的系统未启用IPv6网络功能，这可能会影响下载项目的网络速度。',
    ipv6_dialog_content_2: '请开启IPv6网络以达到最佳的下载体验。',
    ipv6_dialog_content_3: '开启IPv6教程',
    run_button_cmd_content_1:'脚本已更新，请到市场重新下载最新版本以确保项目正常运行。',
    button_ok: '确认',
    button_donot_remind_again: '不再提醒',
    search: "搜索",
    market_filter_price: "价格",
    market_filter_price_free: "免费",
    market_filter_price_paid: "付费",
    market_filter_price_vip: "VIP",
    market_filter_hardware: "设备类型",
    market_filter_hardware_cpu: "CPU",
    market_filter_hardware_nvidia: "N卡",
    market_filter_hardware_amd: "A卡",
    market_filter_platform: "平台",
    market_filter_class: "AI应用",
    market_filter_class_image: "图像",
    market_filter_class_sound: "音频",
    market_filter_class_video: "视频",
    market_filter_class_text: "文本",
    market_filter_tag: "标签",
    market_filter_model: "模型",
    market_filter_plugin: "插件",
    market_filter_workflow: "工作流",
    market_filter_other: "其他",
    market_filter: "筛选",
    market_filter_reset: "清空筛选条件",
    sort_new:"最新发布",
    sort_download:"下载最多",
    sort_like:"点赞最多",
    sort_favorite:"收藏最多",
    app_asce_sort:"升序排序",
    app_desc_sort:"降序排序",
    service_description: "服务说明",
    service_description_1: "尊敬的用户:",
    service_description_2: "1、欢迎使用AIStarter项目管理平台！我们致力于为您提供丰富的AI项目资源，包括AI大模型、插件、工作流、教程等。平台上的所有资源均由用户（创作者）提供或由平台团队从网络搜集整理而来。",
    service_description_3: "2、为了保证资源的高效下载和简化的部署体验，我们推出了VIP服务。VIP会员可享受高速下载和简化的部署服务，提升您的使用效率和体验。此外，用户（创作者）和平台团队在搜集和整理项目时投入了大量时间和精力，特别是在开源项目的基础上进行了部署流程的简化和环境的打包等工作。因此，部分项目在发布时可能会设置一定的辛苦费，以补偿这些努力。我们希望每位用户都能理解并支持这种做法。",
    service_description_4: "3、请注意，AIStarter平台上提供的所有资源仅供个人学习与交流使用。如果您计划将这些资源用于商业目的，请务必购买官方正版授权，以确保合法合规地使用资源。任何未经授权的商业用途均违反了相关法律法规，我们对此类行为不承担任何责任。",
    service_description_5: "感谢您的理解与支持，让我们共同维护一个健康、积极的AI技术交流环境。",
    product_details_author: "发布者",
    product_details_platform: "平台",
    product_details_linking: "关联项目",
    product_details_type1: "模型类型",
    product_details_type2: "插件类型",
    product_details_type3: "工作流类型",
    product_details_device_support: "设备支持",
    product_details_system_requirements: "配置要求",
    product_details_author_nonesystem:"作者未填写",
    product_details_file_size: "文件大小",
    product_details_version: "版本号",
    product_details_amount: "金额",
    product_details_run_operation: "运行操作",
    product_details_release_date: "发布日期",
    product_details_update_date: "更新日期",
    product_details_project_description: "项目描述",
    product_details_project_overview: "项目介绍",
    product_details_related_links: "下载地址",
    product_details_related_links_1: "请登录后查看详细内容",
    product_details_related_links_2: "请订阅后查看详细内容",
    product_details_related_links_3: "请购买后查看详细内容",
    product_details_related_links_4: "暂无相关信息",
    product_details_vram: "显存",
    product_details_add: "添加",
    product_details_buy: "购买",
    product_details_share: "分享",
    product_details_close: "关闭",
    product_details_poster_title: "AIStarter最新版下载地址：",
    product_details_comments: "评论",
    poster_download: "下载海报",
    under_development:"暂时未开放，请稍后探索",
    not_find_project:"没有找到相关信息，去市场下载吧",
    not_project:"没有找到相关信息",
    no_network:"网络连接失败，请检查网络",
    project_status_install:"已安装",
    project_status_add:"已添加,未安装",
    project_status_unzip:"待解压",
    failed_to_get_details:"获取详情失败！没有相关信息",
    product_details_not_login_no_buy:"请先登录再购买！",
    product_details_vip:"会员专属项目，请先订阅再添加！",
    product_details_no_login_no_download:"请先登录后再下载！",
    product_details_in_download:"正在安装",
    product_details_in_loading:"加载中",
    product_details_no_login_no_add:"请先登录再添加！",
    archive_size_calculation_unknown_size:"未知大小",
  },
  shareproject:{
    titleclass: "发布项目",
    titlemodel: "发布模型",
    titleplugin: "发布插件",
    titleworkflow: "发布工作流",
    project_icon_text:"封面图片 尺寸:400x300 格式:png",
    project_nameclass: "项目名称:",
    project_namemodel: "模型名称:",
    project_nameplugin: "插件名称:",
    project_nameworkflow: "工作流名称:",
    project_name_text:"英文、下划线、必须唯一，将作为安装目录",
    project_versionclass: "项目版本:",
    project_versionmodel: "模型版本:",
    project_versionplugin: "插件版本:",
    project_versionworkflow: "工作流版本:",
    project_version_text:"例如1.0.0",
    project_hw: "硬件要求:",
    project_hw1: "CPU",
    project_hw2: "N卡",
    project_hw3: "A卡",
    project_vram:"显卡要求:",
    project_vram_text:"选择最低显卡要求",
    project_price: "定价:",
    project_price1:"免费",
    project_price2:"自定义价格",
    project_price3:"VIP专享",
    project_prices:"价格:",
    project_prices_novip:"非会员价格",
    project_prices_novip_text:"默认就是只能是会员下载，定义后非会员需要按照价格购买",
    project_appiconclass:"应用图标:",
    project_appicon_textclass:"应用图标 推荐尺寸:64x64 格式:png",
    project_appiconmodel:"模型图标:",
    project_appicon_textmodel:"模型图标 推荐尺寸:64x64 格式:png",
    project_appiconplugin:"插件图标:",
    project_appicon_textplugin:"插件图标 推荐尺寸:64x64 格式:png",
    project_appiconworkflow:"工作流图标:",
    project_appicon_textworkflow:"工作流图标 推荐尺寸:64x64 格式:png",
    project_classclass:"项目类型",
    project_classmodel:"模型类型",
    project_classplugin:"插件类型",
    project_classworkflow:"工作流类型",
    project_titleclass:"项目标题:",
    project_titlemodel:"模型标题:",
    project_titleplugin:"插件标题:",
    project_titleworkflow:"工作流标题:",
    project_descclass: "项目描述:",
    project_descmodel: "模型描述:",
    project_descplugin: "插件描述:",
    project_descworkflow: "工作流描述:",
    project_overviewclass: "项目介绍:",
    project_overviewmodel: "模型介绍:",
    project_overviewplugin: "插件介绍:",
    project_overviewworkflow: "工作流介绍:",
    project_url: "相关链接:",
    project_clonelink:"网盘链接:",

    project_button_pack: "打包",
    project_button_smbit: "提交",
    project_radio_contentclass:"不重新打包项目",
    project_radio_content_textclass:"已经发布过项目，且只修改了应用信息，可以勾上这个，加快发布速度",
    project_radio_contentmodel:"不重新打包模型",
    project_radio_content_textmodel:"已经发布过模型，且只修改了模型信息，可以勾上这个，加快发布速度",
    project_radio_contentplugin:"不重新打包插件",
    project_radio_content_textplugin:"已经发布过插件，且只修改了插件信息，可以勾上这个，加快发布速度",
    project_radio_contentworkflow:"不重新打包工作流",
    project_radio_content_textworkflow:"已经发布过工作流，且只修改了工作流信息，可以勾上这个，加快发布速度",

    project_packagclass:"打包项目",
    project_packag_textclass:"只打包项目",
    project_packagmodel:"打包模型",
    project_packag_textmodel:"只打包模型",
    project_packagplugin:"打包插件",
    project_packag_textplugin:"只打包插件",
    project_packagworkflow:"打包工作流",
    project_packag_textworkflow:"只打包工作流",
    project_product_launchclass:"发布项目",
    project_product_launchmodel:"发布模型",
    project_product_launchplugin:"发布插件",
    project_product_launchworkflow:"发布工作流",
    project_product_launch_text:"发布到市场",

    project_packag_button:"打包",
    project_repackag_button:"重新打包",

    project_repackag_title:"重新打包项目需要将原本打包的压缩包删除，是否继续?",
    project_repackag_tit:"提示",

    project_del_success:"删除成功",
    project_repackag_check:"检测到项目有修改，请重新打包分享",

    share_success_copy:"口令复制成功",
  },
  addproject:{
    title: "添加项目",
    project_name1:"AI项目",
    project_name2:"模型",
    project_name3:"插件",
    project_name4:"工作流",
    project_name5:"其他",
    project_onlogin_onadd:"请登录后再添加项目",
    project_onlogin_goguest:"请登录后再查看用户详情",
    project_onlogin_gosendmsg:"请登录后再发送消息",

    project_oncreator_onadd:"请完善个人信息后再添加项目",

    project_folder:"项目目录:",
    project_folder_tip:"英文、下划线、必须唯一，将作为安装目录",
    project_folder_pholder:"位于安装目录 'Products' 文件夹内",
    project_version:"版本号:",
    project_version_pholder:"例如:v1 v1.0 v1.0.0",
    project_related_file:"项目文件",
    project_related_file_tip:"要压缩打包的文件夹。",
    project_related_files:"+ 压缩文件夹",
    project_type:"项目类型:",
    project_icon:"应用图标:",
    project_title:"项目标题:",
    project_title_pholder:"在AI应用和市场展示的标题",
    project_desc: "项目描述:",
    project_desc_pholder:"项目基本信息",

    project_edit: "编辑信息",
    project_edit_script: "新建脚本",
    project_test: "测试运行",
    project_publish: "是否发布",

    project_appicon_text:"应用图标 推荐尺寸:64x64 格式:png",

    project_command_line:"执行目录以及执行命令行",
    project_command_line_title:"cmd执行目录",
    project_command_line_title_pholder:"根目录",

    project_output_form:"输出形式:",
    project_output_form_pholder:"选择输出信息",

    project_output_form_label1:"标准输出",
    project_output_form_label2:"错误输出",

    project_run_command_line:"执行命令行的方法:",
    project_run_command_line_pholder:".\\run.bat 或者 .\\python\\python.exe -u main.py",
    project_run_command_line_pholder2:"例如：.\\清除缓存.bat 或者 .\\python\\python.exe -u web.py",

    project_intg_pkg:"整合包目录",
    project_intg_pkg_pholder:"请选择整合包根目录",

    project_script_mode:"创建脚本",
    project_script_mode_ez:"简单模式",
    project_script_mode_pro:"专业模式",
    project_add_folder:"添加目录",
    project_folder_name:"目录名称:",
    project_folder_name_pholder:"某某某目录 或 模型 例如：根目录，模型目录等……",
    project_folder_name_message:"目录名不能为空",
    project_folder_path:"路径:",
    project_folder_path_pholder:"\aaa\bbb 或者 \aaa",
    project_folder_path_message:"路径不能为空",

    project_add_folder_button:"删除",

    project_callback_output:"回调输出",

    project_run_time:"启动成功判断:",
    project_run_time_pholder:"例子：输入”1000“ 就是一秒 没有结束判断时默认3秒",

    project_end_judge:"结束判断",
    project_end_judge_pholder:"启动成功的关键词,如:Starting",

    project_time_and_judge:"选择回调输出类型",
    project_time_and_judge_value1:"终端输出文本",
    project_time_and_judge_value2:"倒计时",

    project_add_project_success:"创建成功",
    project_add_project_error:"创建失败",
    project_add_project_exist:"项目目录已存在，请更换目录名",
    project_add_project_exist_web:"目录名已被使用，请修改名称",
    project_add_project_exist_server:"服务器错误，请稍后再试",
    project_import_integration_package_success:"导入整合包成功",
    project_import_integration_package_error:"导入整合包失败",

    project_existence_title:"项目已存在，请修改目录名",
    project_needed_script:"勾选需要的脚本",
    project_active_script:"已选中的脚本",

    project_advanced_options:"高级选项",

    project_onjumpurl:"非自动跳转填:",
    project_onjumpurl_pholder:"例如：http://127.0.0.1:7860",

    project_load_prompt:"加载中提示词:",
    project_load_prompt_pholder:"默认：正在启动，请耐心等候！",

    project_related_settings:"相关设置选项",
    project_settings_name:"设置名称:",
    project_settings_name_pholder:"例如：启动选项 等……",
    project_settings_name_message:"设置名称不能为空",
    project_settings_type:"类型:",
    project_settings_type_message:"类型不能为空",
    project_settings_type_pholder:"选择类型",
    project_settings_type_label1:"按钮",
    project_settings_type_label2:"下拉框",

    project_settings_type_options:"类型选项:",
    project_settings_type_options_message:"类型选项不能为空",

    project_settings_visible_content:"可视内容:",
    project_settings_visible_content_pholder:"CPU 或者 GPU 等……",
    project_settings_visible_content_message:"可视内容不能为空",

    project_settings_parameter_values:"参数内容:",
    project_settings_parameter_values_pholder:"--cpu 或者 --gpu=0 等……",
    project_settings_parameter_values_message:"参数内容不能为空",

    project_settings_button_options:"按钮选项:",
    project_settings_button_options_label1:"按钮名称:",
    project_settings_button_options_label1_pholder:"例如：点击清除 等……",
    project_settings_button_options_label2:"按钮类型:",
    project_settings_button_options_label2_1:"主要",
    project_settings_button_options_label2_2:"正确",
    project_settings_button_options_label2_3:"信息",
    project_settings_button_options_label2_4:"警告",
    project_settings_button_options_label2_5:"危险",
    project_settings_button_options_label2_pholder:"选择按钮类型",
    project_settings_button_options_label2_message:"按钮类型不能为空",
    project_settings_button_options_message:"按钮选项不能为空",

    project_settings_preview:"预览:",
    project_settings_preview_tip:"注意:下拉框这个选项对应的参数，需要自己后续手动添加。(TS：需要操作脚本的下一步有直接操作脚本的按钮)",

    project_title_message:"请输入项目标题",
    project_desc_message:"请输入项目描述",
    project_describe_message:"请输入项目介绍",
    project_url_message:"请输入项目相关链接",
    project_cloudlink_message:"请输入网盘链接",
    project_executecmdfunction_message:"请输入执行命令",
    project_gupradio_message:"请选择相关配置",
    project_needgupraw_message:"请选择显卡要求",
    project_appicon_message:"请选择应用图标",
    project_projectname_message:"请输入项目目录",
    project_movefile_message:"相关文件最少输入一个",
    project_filterclass_message:"请选择应用筛选类型！",
    project_no:"项目不存在",
    project_upload_img_error:"请上传项目图片！",
    project_yes:"项目创建成功",
    project_please_error:"请填写正确的信息！",
    project_name_empty:"项目名称不能为空！",


    project_name_message:"目录不能为空",
    project_name_message_error:"目录格式不正确，只支持字母、数字、下划线",

    project_version_message:"版本号不能为空",
    project_version_message_error:"版本号格式，如：v1 v1.0 v1.0.0",

    project_starttestproject:"测试应用",
    project_starttestproject_pholder:"测试应用的回调会出现在这里",
    project_endtestproject:"结束应用",

    project_opentest:"打开脚本调试",

    project_do_not_publish:"不发布应用",
    project_do_publish:"发布应用",

    project_icon_text:"封面图片 尺寸:400x300 格式:png",

    project_back:"上一步",
    project_next:"下一步",
    project_save:"完成",

  },
  login:{
    login_username:"用户名:",
    login_email:"邮箱:",
    login_email_tis:"请输入正确的邮箱!",
    login_password:"密码:",
    login_new_password:"新密码:",
    login_confirm_password:"确认密码:",
    login_confirm_password_tis:"密码与确认密码不一致.",
    login_code:"验证码:",
    login_code_success:"发送验证码成功!",
    login_code_error:"发送验证码失败",
    login_code_error_sending_too_frequently:"发送验证码过于频繁，请稍后再试!",
    login_code_text:"获取验证码",
    login_code_text_wait:"重新获取",
    login_forget_password:"忘记密码",
    login_login:"登录",
    login_login_success:"登录成功!",
    login_login_error:"登录失败!",
    login_register:"注册",
    login_register_success:"注册成功!",
    login_register_error:"注册失败，请重试!",
    login_register_error_email:"邮箱已注册",
    login_register_error_username:"用户名已注册",
    login_user_agreement:"用户协议",
    login_user_agreement_message:"请阅读并同意用户协议",
    login_privacy_policy_text:"我已阅读并同意",

    login_submit:"提交",
    login_reset:"重置",
    login_and_userpassworderror:"用户名或密码错误",
    login_servererror:"服务器错误，请重试!",
    login_email_error:"邮箱验证码错误",
    login_password_vali:"密码必须是长度在6到20之间的字符串，且包含至少一个数字、一个字母和一个特殊字符。",
    login_username_vali:"用户名长度在3到20个字符之间，并且只包含字母和数字",

    login_format_error:"请输入正确格式!",
    login_email_null:"请输入邮箱",
    login_email_url:"请输入正确的邮箱地址",
    login_code_null:"请输入验证码",
    login_password_null:"请输入密码",
    login_confirm_password_null:"请输入确认密码",
    login_password_min:"密码长度不能小于6",
    login_password_max:"密码长度不能大于20",

    login_success:"成功",
    login_database_error:"数据库错误，请重试!",
    login_email_not_exist:"邮箱未注册，请先注册",
    login_invite_code:"邀请码:",
    login_invite_code_placeholder:"请输入邀请码(可选)",
    login_invite_code_error:"邀请码错误",
  },
  homeproject:{
    project_move_folderclass:"项目目录",
    project_move_foldermodel:"模型目录",
    project_move_folderplugin:"插件目录",
    project_move_folderworkflow:"工作流目录",
    project_move_delectclass:"项目卸载",
    project_move_delectmodel:"模型卸载",
    project_move_delectplugin:"插件卸载",
    project_move_delectworkflow:"工作流卸载",
    project_move_topclass:"项目置顶",
    project_move_topmodel:"模型置顶",
    project_move_topplugin:"插件置顶",
    project_move_topworkflow:"工作流置顶",
    project_close_top:"取消置顶",
    project_top:"顶",
    project_move_Import:"离线导入",

    project_move_del_txt:"确定要卸载",
    project_move_del_txt_2:"吗？",
    project_move_del_txt_3:"提示",
    project_move_del_txt_4:"确定",
    project_move_del_txt_5:"取消",

    project_share_editcode:"编辑代码",
    project_share_editcode_save:"保存",
    project_share_editcode_save_ok:"保存成功",
    project_share_editcode_save_error:"保存失败",
    project_share_run:"调试运行",
    project_share_run_start:"开始",
    project_share_run_end:"停止",
    project_share_share:"发布项目",

    project_package_success:"项目打包成功，请上传 \\Share 文件夹的压缩文件到第三方网盘，并填写获取的链接。",
    project_package_error:"打包失败，请重试",
  },
  versionupd:{
    version_upd_title:"更新提示",
    version_upd_button:"立即更新",
    version_upd_tis:"重要提示：请勿将软件安装目录与项目根目录设置在同一位置，以免升级或卸载时误删项目文件；安装或升级前，请确保目录路径不含中文或特殊字符，并选择磁盘空间充足的目录存放文件，同时建议备份重要数据以避免意外丢失。",
    check_update:"检查更新",
    downloading:"下载中",
    download_completed:"下载完成",
    found_new_version:"发现新版本！",
    already_latest_version:"当前已是最新版本！",
    check_update_failed:"检查更新失败",
    post_download_error:"处理下载完成后的操作时发生错误",
    download_failed_retry:"下载失败，请重试",
    download_error_retry:"下载过程中发生错误，请重试",
    download_no_path_warning:"下载完成，但无法获取安装文件路径",
    install_confirm_title:"安装确认",
    install_confirm_message:"下载完成！是否立即安装新版本？\n\n注意：安装过程中应用将会关闭",
    install_now:"立即安装",
    install_later:"稍后安装",
    starting_installer:"正在启动安装程序，应用即将关闭...",
    installer_failed:"启动安装程序失败，请手动运行安装文件",
    native_confirm_message:"自动安装失败，是否打开文件所在目录进行手动安装？",
    auto_install_failed_message:"自动安装失败，是否打开文件所在目录进行手动安装？",
    install_failed_title:"安装失败",
    open_directory:"打开目录",
    download_complete_open_dir_message:"安装文件已下载完成，是否打开文件所在目录？",
    download_complete_title:"下载完成",
    install_operation_error:"处理安装操作时发生错误",
    download_link_unavailable:"下载链接不可用，请稍后重试",
    update_content:"更新内容",
    version_number:"🚀 版本号",
    download_complete_no_path:"下载完成，但无法获取安装文件路径",
    install_file_downloaded_message:"安装文件已下载完成，是否打开文件所在目录？"
  },
  globaldialog:{
    button_ok:"确定"
  },
  imagetxt:{
    img_class_error:"请上传png,jpg,jpeg,tiff格式的图片！",
    img_size_error:"图片大小不能大于200KB!",
    img_size_error2:"图片大小不能大于500KB!",
    img_size_error3:"图片大小不能大于1MB!",
  },
  contextmenu:{
    copy:"复制",
    paste: "粘贴",
    cut: "剪切",
    delete: "删除",
    select_all: "全选",
    undo: "撤销",
    redo: "重做",
    zoom_in: "放大",
    zoom_out: "缩小",
    zoom_reset: "复位",
    zoom_fit: "适应",
    zoom_fit_width: "适应宽度",

    copy_success:"复制成功",
    paste_success:"粘贴成功",
    cut_success:"剪切成功",
    delete_success:"删除成功",
    select_all_success:"全选成功",
    undo_success:"撤销成功",
    redo_success:"重做成功",
    zoom_in_success:"放大成功",
    zoom_out_success:"缩小成功",
    zoom_reset_success:"复位成功",
    zoom_fit_success:"适应成功",

    copy_error:"复制失败",
    paste_error:"粘贴失败",
    cut_error:"剪切失败",
    delete_error:"删除失败",
    select_all_error:"全选失败",
    undo_error:"撤销失败",
    redo_error:"重做失败",
    zoom_in_error:"放大失败",
    zoom_out_error:"缩小失败",
    zoom_reset_error:"复位失败",
  },
  filelist:{
    directory_title:"文件目录筛选",
    directory_search:"输入关键词",
  },
  myproject:{
    myproject_title:"我的项目",
    myproject_search:"查询项目名称",
    table_id:"序号",
    table_username:"用户名",
    table_name:"项目名称",
    table_version:"版本",
    table_platform:"平台",
    table_like:"点赞",
    table_favorite:"收藏",
    table_download:"下载次数",
    table_review:"审核状态",
    table_review_success:"已通过",
    table_review_ing:"审核中",
    table_review_error:"未通过",
    table_operate:"操作",
    table_operate_look:"查看",
    table_operate_del:"删除",
    table_operate_del_success:"删除成功",
    table_operate_del_error:"数据库错误",
    table_operate_del_tis:"确认要删除该项目",
    table_operate_del_title:"提示",
    table_operate_del_ok:"确定",
    table_operate_del_cancel:"取消",
    table_operate_del_cancel_tis:"取消删除",
    table_operate_edit:"编辑",
    table_operate_edit_error:"未找到该插件,请添加后再编辑",
    table_operate_edit_tis:"确认要编辑该项目",
    table_operate_edit_title:"提示",
    table_operate_edit_ok:"确认",
    table_operate_edit_cancel:"取消",
    form_project_query:"项目查询",
    form_platform_query:"平台查询",
    form_platform_query_placeholder:"平台查询",
    form_review_status:"审核状态",
    form_review_status_placeholder:"审核状态",
    form_query_button:"查询",
    form_reset_button:"重置",
    
  },
  myresources:{
    myresources_title:"我的资源",
    form_resource_query:"资源查询",
    form_platform_query:"平台查询",
    form_platform_query_placeholder:"平台查询",
    form_resource_type:"资源类型",
    form_resource_type_placeholder:"资源类型",
    form_review_status:"审核状态",
    form_review_status_placeholder:"审核状态",
    form_query_button:"查询",
    form_reset_button:"重置",
    resource_type_model:"模型",
    resource_type_plugin:"插件",
    resource_type_workflow:"工作流",
    resource_type_other:"其他",
  },
  myfavorites:{
    myfavorites_title:"我的收藏",
    form_project_query:"项目查询",
    form_project_type:"项目类型",
    form_project_type_placeholder:"项目类型",
    form_query_button:"查询",
    form_reset_button:"重置",
    table_project_type:"项目类型",
    table_operate_unfavorite:"取消收藏",
    project_type_app:"应用",
    project_type_model:"模型",
    project_type_plugin:"插件",
    project_type_workflow:"工作流",
    unfavorite_confirm:"是否取消收藏",
  },
  mydevice:{
    mydevice_title:"我的设备",
    device_current:"当前",
    device_delete:"删除",
    delete_success:"删除成功",
  },
  mydownload:{
    mydownload_title:"我的下载",
    form_project_query:"项目查询",
    form_project_type:"项目类型",
    form_project_type_placeholder:"项目类型",
    form_start_time:"开始时间",
    form_end_time:"结束时间",
    form_query_button:"查询",
    form_reset_button:"重置",
    table_project_type:"项目类型",
    table_download_count:"下载次数",
    table_download_time:"下载时间",
    project_type_app:"应用",
    project_type_model:"模型",
    project_type_plugin:"插件",
    project_type_workflow:"工作流",
    delete_confirm:"是否删除该下载记录",
  },
  mybuy: {
    mybuy_title: '购买记录',
    form_date_label: '日期',
    date_placeholder: 'Pick a day',
    table_date: '日期',
    table_order_no: '订单号',
    table_merchant: '商家',
    table_title: '标题',
    table_type: '类型',
    merchant_platform: '平台',
    filter_vip: 'VIP',
    filter_ai_app: 'AI应用',
    filter_ai_model: 'AI模型',
    filter_ai_plugin: 'AI插件',
    filter_ai_workflow: 'AI工作流',
    filter_creator_renewal: '共创者续费',
    channel_vip: 'vip',
    channel_ai_project: 'AI项目',
    channel_ai_model: 'AI模型',
    channel_ai_plugin: 'AI插件',
    channel_ai_workflow: 'AI工作流',
    channel_creator_renewal: '共创者续费'
  },
  mywallet: {
    wallet_title: '我的余额',
    balance_label: '余额',
    withdraw_button: '提现',
    under_review_balance: '审核中的余额',
    under_review_tooltip_title: '什么是审核中余额',
    under_review_tooltip_content: '共创者获得的收益转成余额时，可能存在审核流程，审核中的余额暂时无法提现',
    withdraw_date_reminder: '提现日期提醒',
    withdraw_rule_title: '提现规则',
    withdraw_rule_content: '每月1-10日为提现申请时间。审核通过后将在当月20日之前完成支付。',
    withdraw_details_title: '提现明细',
    recent_date_label: '近期日期',
    date_placeholder: 'Pick a day',
    table_transfer_time: '提现时间',
    table_order_number: '单号',
    table_status: '状态',
    table_tax_amount: '税金',
    table_transfer_balance: '提现金额',
    table_transfer_channel: '提现渠道',
    table_remark: '备注',
    remark_view: '查看',
    remark_none: '无',
    channel_alipay: '支付宝',
    channel_wechat: '微信',
    channel_paypal: 'PayPal',
    channel_bank: '银行卡',
    channel_enterprise: '企业账户',
    status_pending: '待审核',
    status_approved: '审核通过',
    status_transferring: '打款中',
    status_completed: '已完成',
    status_rejected: '已拒绝',
    status_cancelled: '已撤销',
    status_unknown: '未知状态',
    withdraw_min_amount_error: '提现金额不能小于100'
  },
  header:{
    create_project:"发布作品",
    subscribe:"订阅",
    join_member:"成为会员",
    vip_annual_member:"VIP(年会员)",
    vip_lifetime_member:"VIP(永久会员)",
    login:"登录",
    join_creator:"申请成为创作者",
    my_account:"个人中心",
    logout:"退出登录",
    renew:'续费',
  },
  modelproject:{
    project_folder:"模型目录:",
    project_folder_tip:"英文、下划线、必须唯一，将作为安装目录",
    project_folder_pholder:"位于安装目录 'Models' 文件夹内",
    project_version:"版本号:",
    project_version_pholder:"例如:v1 v1.0 v1.0.0",
    project_icon:"模型图标:",
    project_appicon_text:"模型图标 推荐尺寸:64x64 格式:png",
    project_type:"模型类型:",
    project_title:"模型标题:",
    project_title_pholder:"在模型和市场展示的标题",
    project_desc:"模型描述:",
    project_desc_pholder:"模型基本信息",
    project_intg_pkg:"导入模型:",
    project_intg_pkg_pholder:"请选择模型根目录",
    project_existence_title:"项目已存在，请修改目录名",
    project_title_message:"请输入模型标题",
    project_desc_message:"请输入模型描述"
  },
  pluginproject:{
    project_folder:"插件目录:",
    project_folder_tip:"英文、下划线、必须唯一，将作为安装目录",
    project_folder_pholder:"位于安装目录 'Plugins' 文件夹内",
    project_version:"版本号:",
    project_version_pholder:"例如:v1 v1.0 v1.0.0",
    project_icon:"插件图标:",
    project_appicon_text:"插件图标 推荐尺寸:64x64 格式:png",
    project_type:"插件类型:",
    project_title:"插件标题:",
    project_title_pholder:"在插件和市场展示的标题",
    project_desc:"插件描述:",
    project_desc_pholder:"插件基本信息",
    project_intg_pkg:"导入插件:",
    project_intg_pkg_pholder:"请选择插件根目录",
    project_existence_title:"项目已存在，请修改目录名",
    project_title_message:"请输入插件标题",
    project_desc_message:"请输入插件描述"
  },
  workflowproject:{
    project_folder:"工作流目录:",
    project_folder_tip:"英文、下划线、必须唯一，将作为安装目录",
    project_folder_pholder:"位于安装目录 'Workflows' 文件夹内",
    project_version:"版本号:",
    project_version_pholder:"例如:v1 v1.0 v1.0.0",
    project_icon:"工作流图标:",
    project_appicon_text:"工作流图标 推荐尺寸:64x64 格式:png",
    project_type:"工作流类型:",
    project_title:"工作流标题:",
    project_title_pholder:"在工作流和市场展示的标题",
    project_desc:"工作流描述:",
    project_desc_pholder:"工作流基本信息",
    project_intg_pkg:"导入工作流:",
    project_intg_pkg_pholder:"请选择工作流根目录",
    project_existence_title:"项目已存在，请修改目录名",
    project_title_message:"请输入工作流标题",
    project_desc_message:"请输入工作流描述"
  },
  personalcenter:{
    updatapwd:"修改密码",
    oldpwd:"旧密码",
    newpwd:"新密码",
    confirmpwd:"确认密码",
    submit:"确认",
    login_password_vali:"密码必须是长度在6到20之间的字符串，且包含至少一个数字和一个字母",
    confirm_password_vali:"密码与确认密码不一致",
    update_success:"修改密码成功",
    oldpwd_error:"原密码错误",
    update_error:"修改密码失败",
    myaccount:'用户中心',
    mymessage:'我的消息',
    comment_message:'评论消息',
    like_message:'点赞消息',
    myorder:'收益管理',
    mywallet:'我的钱包',
    myincome:'收益中心',
    mydiscounts:'我的优惠',
    userinfo:'用户信息',
    userinfo_update:'修改信息',
    userinfo_updateinfo:'完善信息',
    userinfo_updatepwd:'修改密码',
    myproject:'项目管理',
    myproject_my:'我的项目',
    myresources_my:'我的资源',
    myfavorites:'我的收藏',
    myhistory:'历史记录',
    mydownload:'下载记录',
    myorderhistory:'购买记录',
    collection:'收藏',
    download:'下载',
    likes:'点赞',
    income:'总收益',
    balance:'钱包',
    expire:'到期',
    name:'姓名:',
    idcard:'身份证:',
    idcardexpire:'身份证有效期:',
    data:'日期',
    positiveidcardimgupload:"身份证正反面:",
    positiveidcard:"身份证正面",
    negativeidcard:"身份证反面",
    wechatimage:"微信收款码",
    alipayimage:"支付宝收款码",
    residence:'居住地:',
    placeholderresidence:"请选择居住地",
    wechat:'微信:',
    alipay:'支付宝:',
    bankcard:'银行账号:',
    bankname:'开户银行:',
    save:'提交',
    complete_personal_info:'完善个人信息',
    toggle_sensitive_info:'隐藏/显示敏感信息',
    hidden_info:'*** 隐藏信息 ***',
    image_hidden:'*** 图片已隐藏 ***',
    password_verification:'密码验证',
    enter_login_password:'请输入登录密码',
    password_placeholder:'请输入密码',
    password_verification_failed:'密码验证失败',
    password_cannot_be_empty:'密码不能为空',
    password_verification_success:'密码验证成功',
    password_verification_error:'密码验证出错',
    hide_sensitive_info:'隐藏敏感信息',
    show_sensitive_info:'显示敏感信息',
    enter_password_prompt:'请输入密码以验证身份',
    password_required:'请输入密码',
    password_verify_success:'密码验证成功',
    password_error:'密码错误',
    password_input_cancelled:'密码输入已取消',
    password_verify_failed:'密码验证失败',
    enterprise_certification:'企业认证',
  },
  resconfig:{
    home_resconfig_button:'配置',
    resconfig_title:'项目名称:',
    resconfig_title_vali:"请输入项目名称",
    resconfig_table_name:'项目名字',
    resconfig_ok:'配置',
    resconfig_custom_linking:'自定义关联',
    resconfig_model:'模型',
    resconfig_plugin:'插件',
    resconfig_workflow:'工作流',
    resconfig_configok:'已成功配置到项目',
    resconfig_configno:'配置已取消',
    resconfig_nodisk:'请选择同一磁盘下的文件夹',
  },
  subcenter:{
    time_limited_discount:'限时优惠',
    time_limited:'限时',
    yuan:'元',
    list_price:'原价',
    loyalty_program:'会员计划',
    please_login:'请先登录账号',
    please_wait:'正在请求数据，请稍后！',
    please_wait_no:'获取数据失败!',
    cell_me_phone:'手机',
    cell_me_email:'邮箱',
    cell_me:'请联系我们',
    cell_me_confirm:'确认'
  },
  qrcodepaymentdialog:{
    price:'价格：',
    qrcodeexpire:'二维码已过期，',
    paypalexpire:'PayPal已过期，',
    balance_expire:'余额支付已过期',
    refresh:'刷新',
    protocol:'请阅读勾选同意订阅协议',
    qrcodegenerate:'生成中，请稍候...',
    paypalpayment:'立即支付',
    balancepayment:'请使用余额支付',
    account_balance:'账号余额',
    pay_now:'立即支付',
    subscription_protocol:'我已阅读并同意',
    subscription_protocol_link:'订阅协议',
    discount_placeholder:'请输入优惠码',
    discount:'使用优惠码',
    backtoseller:'返回商家',
    wechatpayment:'请使用微信扫一扫支付',
    alipaypayment:'请使用支付宝扫一扫支付',
    paypalpayments:'请使用PayPal支付',
    stripepayment:'请使用Stripe支付',
    stripepayments:'使用Stripe支付',
    pingpongpayment:'请使用PingPong支付',
    pingpongpayments:'使用PingPong支付',
    createorder:'正在生成订单...',
    createordererror:'创建订单失败，请稍后再试！',
    payment_success:'支付成功！',
    couponcodeempty:'优惠码不能为空！',
    password_confirmation_title:'支付密码确认',
    payment_amount:'支付金额',
    payment_password_placeholder:'请输入支付密码',
    password_required:'请输入支付密码',
    insufficient_balance:'余额不足',
    cancel:'取消',
    confirm_payment:'确认支付',
  },
  guestpage: {
    not_set: '未设置',
    annual_member: '年度会员',
    permanent_member: '永久会员',
    regular_member: '普通会员',
    send_message: '发消息',
    none: '无',
    back_to_personal_center: '点击跳转回个人中心',
    representative_works: '代表作',
    category_resources: '分类资源',
    homepage: '主页',
    likes: '点赞',
    favorites: '收藏'
  },
  mypage: {
    not_set: '未设置',
    none: '无',
    creator: '创作者',
    my_devices: '我的设备'
  },
  myupdateinfo: {
    not_submitted: '未提交',
    under_review: '未审核',
    not_approved: '未通过',
    approved: '已审核',
    id_card_required: '请输入证件号码',
    id_card_length: '证件号码长度应为6-30位',
    id_card_format: '证件号码只能包含字母、数字和短横线',
    name_required: '请输入姓名',
    name_length: '姓名长度应为2-20个字符',
    id_card_expire_required: '请输入证件有效期',
    paypal_format: '请输入正确的Paypal账号（邮箱）',
    paypal_length: 'Paypal账号长度应为5-50位',
    bank_card_required: '请输入银行卡号',
    bank_card_format: '银行卡号应为8-34位字母、数字或空格',
    bank_name_required: '请输入银行名称',
    bank_name_length: '长度为2-50个字符',
    bank_name_format: '仅支持中英文、数字和空格',
    address_length: '居住地址长度应为5-100个字符',
    modify_success: '修改成功',
    payment_method_required: '请填写至少一个支付方式',
    bank_info_required: '请填写银行卡号和开户行',
    id_card_photos_required: '请上传身份证照片',
    id_card_back_required: '请同时上传身份证反面照片',
    id_card_front_required: '请同时上传身份证正面照片',
    form_validation_failed: '表单验证失败'
  },
  myupdate: {
    modify_personal_info: '修改个人信息',
    avatar: '头像',
    alias_chinese_name: '别名(中文名)',
    your_chinese_name: '您的中文名',
    email: '邮箱',
    your_email: '您的邮箱',
    phone_number: '手机号',
    your_phone_number: '您的手机号',
    gender: '性别',
    male: '男',
    female: '女',
    secret: '保密',
    bio: '简介',
    set_your_signature: '设置您的签名- ( ゜- ゜)つロ',
    modify: '修改',
    cancel: '取消',
    upload_png_format: '请上传Png格式的图片！',
    image_size_limit: '图片大小不能大于200KB!',
    phone_required: '请输入手机号',
    phone_format: '请输入有效的国际手机号（如+8613812345678）',
    alias_required: '请输入昵称',
    alias_length: '昵称长度为2-20个字符',
    bio_length: '简介最多100个字符',
    modify_success: '修改成功！'
  },
  mymessage: {
    message_center: '消息中心',
    connected: '已连接',
    connecting: '连接中...',
    reconnect: '重连',
    refresh: '刷新',
    search_contacts: '搜索联系人...',
    no_messages: '暂无消息',
    load_more_contacts: '加载更多联系人',
    online: '在线',
    offline: '离线',
    enter_personal_page: '进入ta的个人主页',
    send_message_hint: '💡 按 Ctrl+Enter 发送消息',
    select_contact_to_chat: '选择联系人开始聊天',
    select_contact_description: '从左侧列表中选择一个联系人来开始对话',
    message_settings: '消息设置',
    message_notifications: '消息提醒',
    sound_notifications: '声音提醒',
    auto_reply: '自动回复',
    auto_reply_placeholder: '设置自动回复消息',
    cancel: '取消',
    save: '保存',
    chat_connection_failed: '聊天连接失败，请检查网络连接',
    chat_connection_error: '建立聊天连接时发生错误',
    select_contact_first: '请先选择一个联系人',
    connection_not_established: '聊天连接未建立，请稍后重试',
    message_content_empty: '消息内容不能为空',
    send_message_failed: '发送消息失败',
    unknown_error: '未知错误',
    messages_refreshed: '消息已刷新',
    refresh_failed: '刷新失败',
    cache_cleared: '缓存已清理',
    clear_cache_failed: '清理缓存失败',
    expired_cache_cleared: '过期缓存已清理',
    clear_expired_cache_failed: '清理过期缓存失败',
    settings_saved: '设置已保存',
    just_now: '刚刚',
    minutes_ago: '分钟前',
    hours_ago: '小时前',
    days_ago: '天前',
    delete_contact: '删除联系人',
    delete_contact_title: '删除联系人',
    delete_contact_confirm: '确定要删除联系人 {name} 吗？此操作将清除所有聊天记录。',
    confirm: '确定',
    contact_deleted: '联系人已删除',
    delete_contact_failed: '删除联系人失败',
    settings: '设置',
    clear_cache: '清除缓存',
    clear_all_cache: '清除所有缓存',
    clear_expired_cache: '清除过期缓存'
  },
  mycommentmessage: {
    project: '项目',
    original_content: '原内容',
    loading: '加载中...',
    scroll_load_more: '滚动加载更多',
    no_more_data: '没有更多数据了',
    no_comment_messages: '暂无评论消息',
    just_now: '刚刚',
    minutes_ago: '{minutes}分钟前',
    hours_ago: '{hours}小时前',
    days_ago: '{days}天前',
    marked_as_read: '已标记为已读',
    mark_failed: '标记失败',
    load_failed: '加载评论消息失败'
  },
  mylikemessage: {
    liked_your: '点赞了你的',
    project: '项目',
    comment: '评论',
    project_content: '项目',
    image: '图片',
    post: '动态',
    content: '内容',
    loading: '加载中...',
    scroll_load_more: '滚动加载更多',
    no_more_data: '没有更多数据了',
    no_like_messages: '暂无点赞消息',
    just_now: '刚刚',
    minutes_ago: '{minutes}分钟前',
    hours_ago: '{hours}小时前',
    days_ago: '{days}天前',
    marked_as_read: '已标记为已读',
    mark_failed: '标记失败',
    load_failed: '加载点赞消息失败'
  },
  myincome: {
    yesterday_income: '昨天收益',
    thirty_days_income: '近30天收益',
    three_months_income: '近三个月收益',
    income_details: '收益明细',
    time_label: '时间',
    date_placeholder: 'Pick a day',
    table_date: '日期',
    table_total: '总计',
    table_reward_amount: '奖励金额',
    table_creation_income: '创作收益',
    table_refund: '退款',
    table_order_desc: '备注'
  },
  mydiscounts: {
    my_coupons: '我的优惠卷',
    coupon_count_unit: '张',
    request_more: '申请更多',
    used_coupons: '已用优惠卷',
    applying_coupons: '申请中的优惠卷',
    application_list: '申请列表',
    time_label: '时间',
    date_placeholder: 'Pick a day',
    table_apply_time: '申请时间',
    table_applicant: '申请人',
    table_apply_count: '申请数量',
    table_issued_count: '实际发放',
    table_review_status: '审核状态',
    table_remark: '备注',
    table_reviewer: '审核人',
    table_review_time: '审核时间',
    my_discount_codes: '我的优惠码',
    table_discount_code: '优惠码',
    table_cashback_amount: '推广奖励',
    table_valid_from: '生效时间',
    table_valid_to: '失效时间',
    table_status: '状态',
    table_user: '使用人',
    table_actions: '操作',
    filter_unused: '未使用',
    filter_used: '已使用',
    filter_expired: '已过期',
    button_copy: '复制',
    button_copy_link: '复制链接',
    button_batch_export: '批量导出',
    copy_success: '复制成功',
    export_confirm_title: '导出优惠卷',
    export_confirm_message: '确定要导出吗？',
    export_confirm_button: '确定',
    export_cancel_button: '取消',
    export_success: '已导出',
    export_filename: '优惠码导出.xlsx',
    export_sheet_name: '优惠码',
    export_headers: {
      serial_number: '序号',
      discount_code: '优惠码',
      min_amount: '最低金额',
      cashback_amount: '返现金额',
      valid_from: '生效时间',
      valid_to: '失效时间',
      usage_status: '使用状态',
      user: '使用人',
      share_link: '分享链接'
    },
    request_more_title: '申请优惠卷',
    request_more_message: '输入想要申请的数量(注：实际发放的数量可能小于申请数量)',
    request_more_button: '申请',
    request_more_error: '只能输入数字',
    status_pending: '待审核',
    status_approved: '已通过',
    status_rejected: '已拒绝',
    coupon_unused: '未使用',
    coupon_used: '已使用',
    coupon_expired: '已过期',
    currency_unit: '元',
    apply_success: '优惠码申请中，请等待审核'
  },
  myinvite: {
    my_invite_code: '我的邀请码',
    share_invite_description: '分享此邀请码给好友，获得推广收益。',
    copy_link: '复制链接',
    generate_invite_code: '点击自动生成您的邀请码',
    custom_invite_code: '自定义生成邀请码',
    parent_bound_cannot_unbind: '邀请人已绑定，无法解绑',
    bind_inviter_placeholder: '绑定邀请人',
    bind_button: '绑定',
    bind_warning: '绑定后无法解绑，请谨慎操作',
    my_invited_count: '我邀请的人数',
    promotion_earnings: '推广收益',
    promotion_commission: '推广分成',
    order_count: '订单数量',
    invite_code_generated: '邀请码生成成功！',
    generate_failed: '生成邀请码失败',
    generate_failed_retry: '生成邀请码失败，请稍后重试',
    invite_code_copied: '邀请码已复制到剪贴板',
    please_enter_invite_code: '请输入邀请码',
    bind_confirm_title: '确认绑定',
    bind_confirm_message: '绑定邀请人后将无法解绑，确定要绑定吗？',
    confirm_bind: '确定绑定',
    cancel: '取消',
    confirm: '确定',
    bind_success: '上级邀请码绑定成功！',
    bind_failed: '绑定失败',
    bind_failed_retry: '绑定失败，请稍后重试',
    get_invite_info_failed: '获取邀请信息失败',
    custom_invite_title: '自定义邀请码',
    custom_invite_prompt: '请输入您的自定义邀请码（6-20个字符，仅支持字母和数字）',
    custom_invite_placeholder: '输入自定义邀请码',
    custom_invite_format_error: '邀请码必须是6-20个字符，仅支持字母和数字',
    custom_invite_success: '自定义邀请码设置成功！',
    custom_invite_failed: '设置自定义邀请码失败',
    custom_invite_failed_retry: '设置自定义邀请码失败，请稍后重试'
  },
  myinvitemenu: {
    my_invite: '我的邀请'
  },
  withdrawdialog: {
    dialog_title: '用户提现',
    amount_label: '提现金额',
    amount_placeholder: '请输入金额',
    method_label: '提现方式',
    method_placeholder: '请选择',
    cancel_button: '取消',
    confirm_button: '确认提现',
    withdraw_types: {
      wechat: '微信',
      alipay: '支付宝',
      bank: '银行卡',
      paypal: 'PayPal',
      enterprise: '企业账户'
    },
    validation: {
      amount_required: '请输入金额',
      amount_must_be_number: '金额必须为数字',
      amount_range: '金额需在{min}~{max}之间',
      amount_decimal: '最多保留两位小数',
      method_required: '请选择提现方式'
    },
    messages: {
      min_amount_error: '最少提现{min}元',
      max_amount_error: '最多提现{max}元',
      success_message: '提现申请成功，金额￥{amount}，预计1-3个工作日到账，请耐心等待审核。'
    }
  },
  userbandialog: {
    dialog_title: '您已被禁止使用AIStarter',
    ban_time_prefix: '封禁时间：',
    ban_time_permanent: '永久封禁',
    ban_reason: '具体原因，请联系客服',
    confirm_button: '知道了'
  },
  devicedialog: {
    dialog_title: '电脑登录设备已超限，请先退出设备',
    dialog_subtitle: '该账号已在其他电脑端登录，您可以对已登录的设备进行退出或登录新账号',
    my_devices: '我的设备',
    current_device: '当前',
    delete_button: '删除',
    device_management_title: '设备管理说明',
    device_management_rules: {
      rule1: '• 每个账号每年仅允许修改设备信息3次，请谨慎操作',
      rule2: '• 删除当前设备后，软件将立即退出并自动登出账号',
      rule3: '• 关闭此窗口后，系统将自动退出当前账号',
      rule4: '注意：删除设备后将无法使用此设备进行登录，请确认后再操作'
    },
    contact_service: '联系客服',
    wechat_scan_alt: '微信扫一扫',
    copy_success: '复制成功',
    copy_log: '已复制：',
    delete_confirm_message: '确定删除[{deviceName}]设备吗？',
    delete_confirm_title: '提示',
    delete_confirm_button: '确定',
    delete_cancel_button: '取消',
    delete_success: '删除成功'
  },
  productdetailsdialog: {
    send_message: '发消息',
    login_required_comments: '请登录后查看评论',
    subscribe_required_comments: '请订阅后查看评论',
    purchase_required_comments: '请购买后查看评论',
    login_required_first: '请先登录',
    favorite_failed: '收藏失败，请稍后重试',
    like_failed: '点赞失败，请稍后重试',
    copy_text: '复制',
    copy_selected_text: '复制选中的文本',
    network_error_message: '网络错误，私信失败'
  },
  commentcomp: {
    like: '点赞',
    favorite: '收藏',
    download: '下载',
    send_message: '发消息',
    get_user_info_failed: '获取用户信息失败',
    get_comments_failed: '获取评论失败',
    network_error_get_comments: '网络错误，获取评论失败',
    network_error_send_message: '网络错误，私信失败',
    comment_success: '评论成功!',
    comment_failed: '评论失败',
    network_error_comment: '网络错误，评论失败',
    operation_failed: '操作失败',
    network_error_operation: '网络错误，操作失败',
    get_reply_failed: '获取回复失败',
    network_error_get_reply: '网络错误，获取回复失败',
    delete_success: '删除成功',
    delete_failed: '删除失败',
    network_error_delete: '网络错误，删除失败',
    image_size_limit: '图片大小不能超过1MB，当前文件大小：',
    image_format_error: '只支持PNG格式的图片，当前文件类型：',
    image_process_failed: '图片处理失败',
    upload_failed: '上传失败',
    image_upload_failed: '图片上传失败'
  },
  operate: {
    report: '举报',
    delete: '删除',
    copy: '复制',
    report_comment: '举报评论',
    report_reason: '举报原因',
    select_report_reason: '请选择举报原因',
    spam_ads: '垃圾广告',
    malicious_attack: '恶意攻击',
    pornographic_content: '色情内容',
    political_sensitive: '政治敏感',
    other: '其他',
    detailed_description: '详细描述',
    describe_report_reason: '请详细描述举报原因...',
    cancel: '取消',
    submit_report: '提交举报',
    fill_complete_info: '请填写完整的举报信息',
    report_success: '举报成功',
    report_failed: '举报失败',
    network_error_report: '网络错误，举报失败',
    no_permission_delete: '您没有权限删除此评论',
    copy_success: '复制成功'
  },
  common: {
    confirm: '确定',
    cancel: '取消',
    close: '关闭'
  },
  enterprise: {
    create_enterprise: '创建企业',
    create_enterprise_cert: '创建企业认证',
    create_enterprise_desc: '创建一个新的企业组织',
    join_enterprise: '加入企业',
    join_enterprise_desc: '通过企业代码加入现有企业',
    enterprise_info: '企业信息',
    enterprise_name: '企业名称',
    enterprise_code: '企业代码',
    enterprise_desc: '企业描述',
    credit_code: '统一社会信用代码',
    legal_person_name: '法人姓名',
    business_license: '营业执照',
    id_card_front: '法人身份证正面',
    id_card_back: '法人身份证反面',
    member_count: '成员数量',
    join_date: '加入时间',
    leave_enterprise: '退出企业',
    enter_enterprise_name: '请输入企业名称',
    enter_enterprise_desc: '请输入企业描述',
    enter_description: '请输入企业描述',
    enter_enterprise_code: '请输入企业代码',
    enter_credit_code: '请输入统一社会信用代码',
    enter_legal_person_name: '请输入法人姓名',
    upload_business_license: '上传营业执照',
    upload_id_card_front: '上传身份证正面',
    upload_id_card_back: '上传身份证反面',
    create: '创建',
    join: '加入',
    name_required: '企业名称不能为空',
    name_length: '企业名称长度应在2-50个字符之间',
    desc_length: '企业描述不能超过200个字符',
    code_required: '企业代码不能为空',
    code_length: '企业代码长度应在6-20个字符之间',
    credit_code_required: '统一社会信用代码不能为空',
    credit_code_format: '统一社会信用代码格式不正确',
    legal_person_required: '法人姓名不能为空',
    legal_person_length: '法人姓名长度应在2-20个字符之间',
    business_license_required: '请上传营业执照',
    id_card_front_required: '请上传法人身份证正面',
    id_card_back_required: '请上传法人身份证反面',
    create_success: '企业创建成功',
    create_failed: '企业创建失败',
    join_success: '加入企业成功',
    join_failed: '加入企业失败',
    leave_confirm: '确定要退出当前企业吗？退出后将无法访问企业相关资源。',
    leave_success: '退出企业成功',
    leave_failed: '退出企业失败',
    status_pending: '待审核',
    status_approved: '已审核',
    status_rejected: '未通过',
    edit_info: '编辑信息',
    edit_enterprise_info: '编辑企业信息',
    submit_date: '提交日期',
    audit_date: '审核日期',
    reject_reason: '驳回原因',
    update: '更新',
    enter_bank_card: '请输入银行卡号',
    enter_bank_name: '请输入银行名称',
    cancel_association: '取消关联',
    associate_cert: '关联认证',
    associate: '关联',
    update_enterprise_info: '更新企业信息',
    exit_under_review: '退出申请审核中',
    exit_application_reviewing: '退出申请正在审核中',
    exit_review_message: '您的退出申请正在审核中，请耐心等待',
    contact_admin_or_support: '请联系管理员或客服',
    create_cert_failed: '创建认证失败',
    join_failed_retry: '加入企业失败，请稍后重试',
    enter_exit_reason: '请输入退出原因',
    exit_enterprise: '退出企业',
    confirm_exit: '确认退出',
    enter_exit_reason_placeholder: '请输入退出原因（可选）',
    exit_application_submitted: '退出申请已提交',
    exit_failed: '退出申请失败',
    exit_failed_retry: '退出申请失败，请稍后重试',
    update_success: '更新企业信息成功',
    update_failed: '更新企业信息失败',
    code_copied: '企业代码已复制到剪贴板',
    join_under_review: '加入申请审核中',
    join_application_reviewing: '加入申请正在审核中',
    join_review_message: '您的加入申请正在审核中，请耐心等待管理员审核'
  }
};
